using System.Collections.Generic;

namespace Sporae.UI.UIToolkit.NotificationsFoundation
{
    /// <summary>
    /// Default TypeSpec list (ex novo) — usata se non esiste un asset Registry in Resources.
    /// </summary>
    public static class NotificationTypeSpecDefaults
    {
        public static IReadOnlyList<NotificationTypeSpec> BuildDefaults()
        {
            // NOTE: templates sono localizzati IT/EN. Parametri via {token}.
            // NOTE: Cooldown suggeriti sono conservativi per evitare spam.

            var list = new List<NotificationTypeSpec>
            {
                // ===== AUTOMATICHE / ECOSYSTEM =====
                Spec("SYS-100", NotificationCategory.System, NotificationSeverity.Info, NotificationChannel.Gameplay, false, false, false, 30f,
                    "notif.sys100",
                    "Sistema di condensazione ottimale",
                    "Condensation system optimal",
                    "La condensazione nella Dome è in range ottimale.\nRaccogli acqua dal serbatoio quando disponibile."),

                Spec("ACT-050", NotificationCategory.Actions, NotificationSeverity.Warning, NotificationChannel.Gameplay, false, false, true, 20f,
                    "notif.act050",
                    "Punti azione bassi",
                    "Low action points",
                    "Stai per esaurire i punti azione.\nRiposa o usa consumabili (es. acqua) per recuperare azioni."),

                Spec("CRY-777", NotificationCategory.Economy, NotificationSeverity.Info, NotificationChannel.Gameplay, false, false, false, 3f,
                    "notif.cry777",
                    "Scambio completato {delta} CRY",
                    "Trade completed {delta} CRY",
                    "Transazione CRY completata.\nI CRY sono la valuta principale per acquisti e costi fissi (LED, ecc.)."),

                // ===== TOPBAR =====
                Spec("SYS-001", NotificationCategory.TopBar, NotificationSeverity.Info, NotificationChannel.Gameplay, false, false, false, 10f,
                    "notif.sys001",
                    "Pannello WIKI aperto",
                    "Wiki database accessed",
                    "Hai aperto il pannello WIKI.\nQui puoi consultare le specie sbloccate e i dati sulle piante."),
                Spec("SYS-002", NotificationCategory.TopBar, NotificationSeverity.Info, NotificationChannel.Gameplay, false, false, false, 10f,
                    "notif.sys002",
                    "Pannello impostazioni aperto",
                    "Settings panel opened",
                    "Pannello impostazioni di gioco aperto.\nQui puoi salvare, caricare e modificare opzioni."),
                Spec("SYS-003", NotificationCategory.TopBar, NotificationSeverity.Success, NotificationChannel.Gameplay, false, false, false, 3f,
                    "notif.sys003",
                    "Gioco salvato correttamente",
                    "Game saved successfully",
                    "Salvataggio completato.\nI progressi sono stati scritti su disco."),
                Spec("SYS-004", NotificationCategory.TopBar, NotificationSeverity.Warning, NotificationChannel.Gameplay, false, false, false, 8f,
                    "notif.sys004",
                    "Salvataggio non riuscito",
                    "Save failed",
                    "Impossibile salvare la partita.\nRiprova o verifica spazio su disco."),
                Spec("SYS-999", NotificationCategory.TopBar, NotificationSeverity.Warning, NotificationChannel.Gameplay, false, false, false, 10f,
                    "notif.sys999",
                    "Uscita da SPORIUM...",
                    "Exiting SPORIUM...",
                    "Stai uscendo dal gioco.\nAssicurati di aver salvato se necessario."),

                // ===== MISSIONS =====
                Spec("MIS-DONE", NotificationCategory.System, NotificationSeverity.Success, NotificationChannel.Gameplay, false, false, false, 2f,
                    "notif.mis_done",
                    "Missione completata: {title}",
                    "Mission completed: {title}",
                    "La missione è stata completata.\nRicompensa assegnata."),
                Spec("MIS-NEW", NotificationCategory.System, NotificationSeverity.Info, NotificationChannel.Gameplay, false, false, false, 2f,
                    "notif.mis_new",
                    "Nuova missione: {title}",
                    "New mission: {title}",
                    "Una nuova missione è stata assegnata.\nControlla il pannello missioni per i dettagli."),

                // ===== PLAYER — Cap azioni / idratazione movimento =====
                Spec("PLY-ACT-CAP-CHG", NotificationCategory.Actions, NotificationSeverity.Info, NotificationChannel.Gameplay, false, false, false, 18f,
                    "notif.ply_act_cap",
                    "Budget azioni: {prev} → {max}",
                    "Action budget: {prev} → {max}",
                    "Il numero massimo di azioni giornaliere è cambiato (colazione, fame o nuovo giorno).\nControlla la barra AZIONI in alto."),
                Spec("PLY-HYD-GAIN", NotificationCategory.Player, NotificationSeverity.Success, NotificationChannel.Gameplay, false, false, false, 1f,
                    "notif.ply_hyd_gain",
                    "H +{delta}% (→ {h}%)",
                    "H +{delta}% (→ {h}%)",
                    "Hai bevuto o mangiato un alimento idratante: idratazione recuperata."),

                Spec("PLY-HYD-WALK-OK", NotificationCategory.TopBar, NotificationSeverity.Success, NotificationChannel.Gameplay, false, false, false, 28f,
                    "notif.ply_hyd_ok",
                    "Velocità movimento: normale (H {h}%)",
                    "Movement speed: normal (H {h}%)",
                    "Idratazione sopra la soglia: nessuna penalità alla velocità di camminata."),
                Spec("PLY-HYD-WALK-MID", NotificationCategory.TopBar, NotificationSeverity.Warning, NotificationChannel.Gameplay, false, false, false, 32f,
                    "notif.ply_hyd_mid",
                    "Camminata rallentata (H {h}% — fascia 26–50%)",
                    "Slower walking (H {h}% — 26–50% band)",
                    "Idratazione sotto il 50%: penalità moderata alla velocità di movimento. Bevi o consuma cibi idratanti."),
                Spec("PLY-HYD-WALK-LOW", NotificationCategory.TopBar, NotificationSeverity.Warning, NotificationChannel.Gameplay, false, false, false, 32f,
                    "notif.ply_hyd_low",
                    "Camminata molto rallentata (H {h}% — ≤25%)",
                    "Much slower walking (H {h}% — ≤25%)",
                    "Disidratazione critica per lo spostamento: penalità severa. Rischio altro se resti a lungo senza reintegrare."),
                Spec("PLY-HYD-WALK-BETTER", NotificationCategory.TopBar, NotificationSeverity.Info, NotificationChannel.Gameplay, false, false, false, 28f,
                    "notif.ply_hyd_better",
                    "Penalità movimento ridotta (H {h}%)",
                    "Movement penalty reduced (H {h}%)",
                    "L’idratazione è salita: la penalità alla camminata è meno severa (resti sotto il 50%)."),

                // ===== DOME — Indice mutazione (Task 7, soglie HUD) =====
                Spec("DOME-IM-MID", NotificationCategory.Ecosystem, NotificationSeverity.Warning, NotificationChannel.Gameplay, false, false, false, 48f,
                    "notif.dome_im_mid",
                    "Pressione mutazionale in salita ({pct}%)",
                    "Mutation pressure rising ({pct}%)",
                    "L’Indice di Mutazione ha superato la prima soglia (oltre ~33%).\nPiù variabilità genetica: monitora le piante sensibili e il Lab."),
                Spec("DOME-IM-HIGH", NotificationCategory.Ecosystem, NotificationSeverity.Warning, NotificationChannel.Gameplay, false, false, false, 72f,
                    "notif.dome_im_high",
                    "IM elevato ({pct}%) — mutazioni più probabili",
                    "High mutation index ({pct}%) — mutations more likely",
                    "Oltre ~66% l’ambiente favorisce mutazioni spontanee e tratti inediti.\nÈ opportunità e rischio: stabilizza se ti serve prevedibilità."),
                Spec("DOME-MUT-PLANT", NotificationCategory.Pot, NotificationSeverity.Warning, NotificationChannel.Gameplay, false, false, false, 5f,
                    "notif.dome_mut_plant",
                    "Mutazione spontanea — {plantName} ({potId})",
                    "Spontaneous mutation — {plantName} ({potId})",
                    "{detail}\nEffetti allineati ai tratti in tempo reale; verifica lo stato al terminale o sulla card."),
                Spec("DOME-MUT-WATCH", NotificationCategory.Ecosystem, NotificationSeverity.Info, NotificationChannel.Gameplay, false, false, false, 24f,
                    "notif.dome_mut_watch",
                    "Pressione mutazionale elevata ({pct}%) — monitora le colture",
                    "High mutation pressure ({pct}%) — watch your crops",
                    "L’Indice di Mutazione è alto e almeno una pianta è nella fascia livello per mutazioni spontanee.\nOggi le variazioni sono più probabili: controlla terminali e HUD."),

                // ===== ROOMS =====
                Spec("PLT-101", NotificationCategory.Room, NotificationSeverity.Info, NotificationChannel.Gameplay, false, false, false, 8f,
                    "notif.plt101",
                    "Dati pianta consultati",
                    "Plant data accessed",
                    "Hai aperto i dettagli di una pianta.\nQui vedi stadio, deriva pH, requisiti e azioni disponibili."),
                Spec("LAB-001", NotificationCategory.Room, NotificationSeverity.Info, NotificationChannel.Gameplay, false, false, false, 8f,
                    "notif.lab001",
                    "Laboratorio accesso effettuato",
                    "Laboratory accessed",
                    "Sei entrato nel Laboratorio.\nQui puoi usare Incubatore, Extractor, Catalizzatore e Fusione."),
                Spec("DOR-001", NotificationCategory.Room, NotificationSeverity.Info, NotificationChannel.Gameplay, false, false, false, 8f,
                    "notif.dor001",
                    "Dormitorio accesso effettuato",
                    "Dormitory accessed",
                    "Accesso al Dormitorio.\nQui puoi riposare e recuperare punti azione."),
                Spec("SEED-001", NotificationCategory.Room, NotificationSeverity.Info, NotificationChannel.Gameplay, false, false, false, 8f,
                    "notif.seed001",
                    "Archivio semi aperto",
                    "Seed Archive accessed",
                    "Archivio semi aperto.\nConsulta e gestisci i semi disponibili per la semina."),
                Spec("KTCH-001", NotificationCategory.Room, NotificationSeverity.Info, NotificationChannel.Gameplay, false, false, false, 8f,
                    "notif.ktch001",
                    "Terminale cucina: accesso effettuato",
                    "Kitchen terminal accessed",
                    "Terminale cucina aperto.\nProduci cibo, acqua potabile e gestisci le risorse alimentari."),
                Spec("MKT-666", NotificationCategory.Room, NotificationSeverity.Warning, NotificationChannel.Gameplay, false, false, false, 8f,
                    "notif.mkt666",
                    "Ingresso al Mercato Nero...",
                    "Entering Black Market...",
                    "Stai accedendo al Mercato Nero.\nZone a reputazione e scambi particolari."),

                // ===== LAB ACTIONS (codici univoci OK/FAIL) =====
                Spec("LAB-INC-OK", NotificationCategory.Lab, NotificationSeverity.Success, NotificationChannel.Gameplay, false, false, false, 0f,
                    "notif.lab_inc_ok",
                    "Incubazione riuscita! Semi ottenuti (x{count}).",
                    "Incubation successful! Seeds obtained (x{count}).",
                    "L'Incubatore ha prodotto semi.\nRitirali dal macchinario per aggiungerli all'archivio."),
                Spec("LAB-INC-FAIL", NotificationCategory.Lab, NotificationSeverity.Danger, NotificationChannel.Gameplay, false, false, false, 0f,
                    "notif.lab_inc_fail",
                    "Incubazione fallita. Seme scartato.",
                    "Incubation failed. Seed discarded.",
                    "L'incubazione non è andata a buon fine.\nIl seme è stato perso; puoi riprovare con un altro."),
                Spec("LAB-INC-PROGRESS", NotificationCategory.Lab, NotificationSeverity.Warning, NotificationChannel.Gameplay, false, false, false, 3f,
                    "notif.lab_inc_progress",
                    "Incubazione in corso… giorno {day}",
                    "Incubation in progress.. day {day}",
                    "L'Incubatore sta processando il seme.\nAttendi il completamento per ritirare i semi."),
                Spec("LAB-INC-DONE", NotificationCategory.Lab, NotificationSeverity.Success, NotificationChannel.Gameplay, false, false, false, 0f,
                    "notif.lab_inc_done",
                    "Raccolto in Incubatore: {itemName} x{quantity}{profile}",
                    "Collected in Incubator: {itemName} x{quantity}{profile}",
                    "Incubazione completata.\n{detail}"),
                Spec("LAB-INC-X-INCOMPLETE", NotificationCategory.Lab, NotificationSeverity.Warning, NotificationChannel.Gameplay, false, false, false, 4f,
                    "notif.lab_inc_x_incomplete",
                    "Incubatore: con Reagente X completa famiglia, tratti e nome.",
                    "Incubator: with Reagent X complete family, traits, and name.",
                    "Per avviare con Reagente X servono famiglia, tratti validi e nome pianta.\nCompila i campi nel pannello Incubatore."),
                Spec("LAB-GRF-OK", NotificationCategory.Lab, NotificationSeverity.Success, NotificationChannel.Gameplay, false, false, false, 0f,
                    "notif.lab_grf_ok",
                    "Innesto riuscito! Creato {seedCode}",
                    "Graft successful! {seedCode} created",
                    "Innesto completato con successo.\nIl nuovo seme è disponibile per la semina."),
                Spec("LAB-GRF-FAIL", NotificationCategory.Lab, NotificationSeverity.Danger, NotificationChannel.Gameplay, false, false, false, 0f,
                    "notif.lab_grf_fail",
                    "Innesto fallito. Residuo organico formato.",
                    "Graft failed. Organic residue formed.",
                    "L'innesto non è riuscito.\nSi è formato residuo organico; puoi riprovare con altri semi."),
                Spec("INV-SPR", NotificationCategory.Inventory, NotificationSeverity.Info, NotificationChannel.Gameplay, false, false, false, 2f,
                    "notif.inv_spr",
                    "Raccolte {amount} spore",
                    "Collected {amount} spores",
                    "Spore aggiunte all'inventario.\nUsale al Microscopio o in altri processi del Lab."),
                Spec("LAB-MIC", NotificationCategory.Lab, NotificationSeverity.Info, NotificationChannel.Gameplay, false, false, false, 5f,
                    "notif.lab_mic",
                    "Microscopio caricato con {sporeCode}",
                    "Microscope loaded with {sporeCode}",
                    "Il Microscopio ha una spora caricata.\nUsalo per analisi o per preparare campioni."),
                Spec("LAB-PIP", NotificationCategory.Lab, NotificationSeverity.Info, NotificationChannel.Gameplay, false, false, false, 5f,
                    "notif.lab_pip",
                    "Pipetta caricata con {sporeCode}",
                    "Pipette loaded with {sporeCode}",
                    "La Pipetta contiene una spora.\nUsala nella Fusione per creare Pre-Seed."),
                Spec("LAB-EXT-START", NotificationCategory.Lab, NotificationSeverity.Warning, NotificationChannel.Gameplay, false, false, false, 3f,
                    "notif.lab_ext_start",
                    "Estrazione in corso… {percent}%",
                    "Spore extraction in progress.. {percent}%",
                    "L'Extractor sta estraendo spore.\nAttendi il completamento per ritirare l'output."),
                Spec("LAB-EXT-DONE", NotificationCategory.Lab, NotificationSeverity.Success, NotificationChannel.Gameplay, false, false, false, 0f,
                    "notif.lab_ext_done",
                    "Estrazione completata. Ritira il materiale (x{count}) dall'Extractor.",
                    "Extraction complete. Collect output (x{count}) from Extractor.",
                    "Estrazione terminata.\nRitira le spore dall'Extractor per aggiungerle all'inventario."),
                Spec("LAB-EXT-RITIRA", NotificationCategory.Lab, NotificationSeverity.Success, NotificationChannel.Gameplay, false, false, false, 0f,
                    "notif.lab_ext_ritira",
                    "Materiale ritirato (x{count}) dall'Extractor.",
                    "Output collected (x{count}) from Extractor.",
                    "Materiale ritirato dall'Extractor.\nLe spore sono ora nel tuo inventario."),
                Spec("LAB-EXT-VARIANT", NotificationCategory.Lab, NotificationSeverity.Info, NotificationChannel.Gameplay, false, false, false, 12f,
                    "notif.lab_ext_variant",
                    "Doppia linea genetica dalle spore",
                    "Dual genetic line from spores",
                    "Questa estrazione ha prodotto due spore RAW: una replica la madre, l’altra ha profilo genetico diverso (Fisso / Stabile / Instabile).\nControlla gli stack in inventario prima del Lab — l’esito non era garantito a priori."),
                Spec("LAB-CAT-PROGRESS", NotificationCategory.Lab, NotificationSeverity.Warning, NotificationChannel.Gameplay, false, false, false, 3f,
                    "notif.lab_cat_progress",
                    "Maturazione in corso… giorno {day}",
                    "Spore maturation in progress.. day {day}",
                    "Il Catalizzatore sta maturando le spore.\nAttendi il giorno indicato per ritirarle."),
                Spec("LAB-CAT-DONE", NotificationCategory.Lab, NotificationSeverity.Success, NotificationChannel.Gameplay, false, false, false, 0f,
                    "notif.lab_cat_done",
                    "Spora maturata pronta (x{count}). Ritira dal Catalizzatore.",
                    "Mature spore ready (x{count}). Collect from Catalyser.",
                    "Le spore sono mature.\nRitirale dal Catalizzatore per usarle."),
                Spec("LAB-CAT-RITIRA", NotificationCategory.Lab, NotificationSeverity.Success, NotificationChannel.Gameplay, false, false, false, 0f,
                    "notif.lab_cat_ritira",
                    "Raccolta: spore maturate x{amount}",
                    "Collected Mature Spore x{amount}",
                    "Spore mature ritirate.\nSono disponibili nell'inventario per il Lab."),
                Spec("LAB-FUS-PROGRESS", NotificationCategory.Lab, NotificationSeverity.Warning, NotificationChannel.Gameplay, false, false, false, 3f,
                    "notif.lab_fus_progress",
                    "Fusione in corso… {percent}%",
                    "Fusion in progress.. {percent}%",
                    "La Fusione è in corso.\nAttendi il 100% per ritirare il Pre-Seed dalla Pipette."),
                Spec("LAB-FUS-DONE", NotificationCategory.Lab, NotificationSeverity.Success, NotificationChannel.Gameplay, false, false, false, 0f,
                    "notif.lab_fus_done",
                    "Fusione completata. Ritira Pre-Seed (x{count}) dalla Pipette.",
                    "Fusion complete. Collect Pre-Seed (x{count}) from the Pipette.",
                    "Fusione completata.\nRitira il Pre-Seed dalla Pipette per portarlo all'Incubatore."),
                Spec("LAB-FUS-RITIRA", NotificationCategory.Lab, NotificationSeverity.Success, NotificationChannel.Gameplay, false, false, false, 0f,
                    "notif.lab_fus_ritira",
                    "Pre-Seed ritirato (x{count}) dalla Pipette.",
                    "Pre-Seed collected (x{count}) from the Pipette.",
                    "Pre-Seed ritirato.\nPuoi incubarlo per ottenere un nuovo seme."),

                // ===== KITCHEN / FOOD ROOM (cumulative come Lab) =====
                Spec("KTCH-FOOD-PROGRESS", NotificationCategory.Room, NotificationSeverity.Warning, NotificationChannel.Gameplay, false, false, false, 3f,
                    "notif.ktch_food_progress",
                    "Colture in corso — {daysRemaining} giorni al completamento",
                    "Crops in progress — {daysRemaining} days to completion",
                    "La cucina sta producendo cibo.\nAttendi i giorni indicati per la raccolta."),
                Spec("KTCH-FOOD-DONE", NotificationCategory.Room, NotificationSeverity.Success, NotificationChannel.Gameplay, false, false, false, 0f,
                    "notif.ktch_food_done",
                    "Cibo pronto per la raccolta (x{count}). Ritira dalla cucina.",
                    "Food ready for collection (x{count}). Collect from the kitchen.",
                    "Produzione completata.\nVai in cucina e ritira per aggiungere all'inventario."),
                Spec("KTCH-FOOD-RITIRA", NotificationCategory.Room, NotificationSeverity.Success, NotificationChannel.Gameplay, false, false, false, 0f,
                    "notif.ktch_food_ritira",
                    "Raccolto: {foodType} x{count}",
                    "Collected: {foodType} x{count}",
                    "Cibo ritirato dalla cucina.\nUsalo per idratazione o altri scopi."),
                Spec("KTCH-FOOD-ON", NotificationCategory.Room, NotificationSeverity.Info, NotificationChannel.Gameplay, false, false, false, 1f,
                    "notif.ktch_food_on",
                    "Sintetizzatore alimentare attivo (5 CRY/giorno)",
                    "Food synthesizer online (5 CRY/day)",
                    "Il sintetizzatore e attivo: le colture avanzano al cambio giorno."),
                Spec("KTCH-FOOD-OFF", NotificationCategory.Room, NotificationSeverity.Warning, NotificationChannel.Gameplay, false, false, false, 1f,
                    "notif.ktch_food_off",
                    "Sintetizzatore alimentare spento",
                    "Food synthesizer offline",
                    "Il sintetizzatore e spento: nessun costo giornaliero e colture in pausa."),
                Spec("KTCH-WAT-PROGRESS", NotificationCategory.Room, NotificationSeverity.Warning, NotificationChannel.Gameplay, false, false, false, 3f,
                    "notif.ktch_wat_progress",
                    "Potabilizzazione in corso… {percent}%",
                    "Water purification in progress… {percent}%",
                    "La cucina sta potabilizzando acqua.\nAttendi il completamento per ritirare l'acqua potabile."),
                Spec("KTCH-WAT-DONE", NotificationCategory.Room, NotificationSeverity.Success, NotificationChannel.Gameplay, false, false, false, 0f,
                    "notif.ktch_wat_done",
                    "Acqua potabile pronta (x{count}). Vai in cucina e usa «Raccogli» per ritirare.",
                    "Potable water ready (x{count}). Go to Kitchen and click Collect to retrieve.",
                    "Acqua potabile pronta.\nRitirala dalla cucina per bere e recuperare azioni."),
                Spec("KTCH-WAT-RITIRA", NotificationCategory.Room, NotificationSeverity.Success, NotificationChannel.Gameplay, false, false, false, 0f,
                    "notif.ktch_wat_ritira",
                    "Raccolto: Acqua potabile x{count}",
                    "Collected: Potable water x{count}",
                    "Acqua potabile ritirata.\nConsumala per idratazione e punti azione."),
                Spec("KTCH-PTRY-ON", NotificationCategory.Room, NotificationSeverity.Info, NotificationChannel.Gameplay, false, false, false, 1f,
                    "notif.ktch_pantry_on",
                    "Dispensa refrigerata attiva (5 CRY/giorno)",
                    "Refrigerated pantry online (5 CRY/day)",
                    "La dispensa e attiva: conserva cibo senza deterioramento finche resta accesa."),
                Spec("KTCH-PTRY-OFF", NotificationCategory.Room, NotificationSeverity.Warning, NotificationChannel.Gameplay, false, false, false, 1f,
                    "notif.ktch_pantry_off",
                    "Dispensa refrigerata disattivata",
                    "Refrigerated pantry offline",
                    "La dispensa e spenta: nessun costo giornaliero; gli alimenti dentro iniziano a deperire."),
                Spec("KTCH-PTRY-DECAY-TICK", NotificationCategory.Room, NotificationSeverity.Warning, NotificationChannel.Gameplay, false, false, false, 0f,
                    "notif.ktch_pantry_decay_tick",
                    "Dispensa spenta: {count} alimento/i in deperimento",
                    "Pantry offline: {count} food item(s) decaying",
                    "La dispensa e spenta: il cibo conservato perde qualita ogni giorno come in borsa."),
                Spec("VAULT-SS-ON", NotificationCategory.Room, NotificationSeverity.Info, NotificationChannel.Gameplay, false, false, false, 1f,
                    "notif.vault_ss_on",
                    "Seed Storage attivo (conservazione criogenica)",
                    "Seed Storage online (cryogenic preservation)",
                    "Il Seed Storage e acceso: nessun decadimento per gli oggetti idonei finche resta attivo."),
                Spec("VAULT-SS-OFF", NotificationCategory.Room, NotificationSeverity.Warning, NotificationChannel.Gameplay, false, false, false, 1f,
                    "notif.vault_ss_off",
                    "Seed Storage spento: i contenuti iniziano a deperire",
                    "Seed Storage offline: contents starting to decay",
                    "Il Seed Storage e spento: nessun costo giornaliero; gli oggetti dentro deperiscono come in inventario."),
                Spec("VAULT-SS-DECAY-TICK", NotificationCategory.Room, NotificationSeverity.Warning, NotificationChannel.Gameplay, false, false, false, 0f,
                    "notif.vault_ss_decay_tick",
                    "Seed Storage spento: {count} oggetto/i in deperimento",
                    "Seed Storage offline: {count} item(s) decaying",
                    "Il Seed Storage e spento: la merce depositata perde qualita ogni giorno."),
                Spec("KTCH-PTRY-IN", NotificationCategory.Room, NotificationSeverity.Success, NotificationChannel.Gameplay, false, false, false, 0f,
                    "notif.ktch_pantry_in",
                    "Deposito dispensa: {itemName} x{count}",
                    "Pantry stored: {itemName} x{count}",
                    "Gli alimenti sono stati trasferiti dalla borsa alla dispensa."),
                Spec("KTCH-PTRY-OUT", NotificationCategory.Room, NotificationSeverity.Info, NotificationChannel.Gameplay, false, false, false, 0f,
                    "notif.ktch_pantry_out",
                    "Prelievo dispensa: {itemName} x{count}",
                    "Pantry retrieved: {itemName} x{count}",
                    "Gli alimenti sono tornati dalla dispensa all'inventario."),

                // ===== POT / PLANT ACTIONS =====
                Spec("POT-PLANT-OK", NotificationCategory.Pot, NotificationSeverity.Success, NotificationChannel.Gameplay, false, false, false, 0f,
                    "notif.pot_plant_ok",
                    "{plantName} piantata con successo",
                    "{plantName} planted successfully",
                    "La pianta è stata messa nel vaso.\nMonitora irrigazione, LED e pH per la crescita."),
                Spec("POT-PLANT-IRR-OK", NotificationCategory.Pot, NotificationSeverity.Success, NotificationChannel.Gameplay, false, false, false, 0f,
                    "notif.pot_plant_irr_ok",
                    "{plantName} piantata e irrigata",
                    "{plantName} planted and irrigated",
                    "Pianta piantata con irrigazione attiva.\nL'idratazione parte da livello buono."),
                Spec("POT-REMOVE", NotificationCategory.Pot, NotificationSeverity.Info, NotificationChannel.Gameplay, false, false, false, 1f,
                    "notif.pot_remove",
                    "Pianta rimossa dal vaso",
                    "Plant removed from pot",
                    "La pianta è stata sradicata dal vaso.\nIl vaso è di nuovo libero per una nuova semina."),
                Spec("POT-HARVEST-OK", NotificationCategory.Pot, NotificationSeverity.Success, NotificationChannel.Gameplay, false, false, false, 0f,
                    "notif.pot_harvest_ok",
                    "Raccolto ottenuto",
                    "Harvest collected",
                    "Raccolto completato.\nIl prodotto è stato aggiunto all'inventario."),
                Spec("POT-W01", NotificationCategory.Pot, NotificationSeverity.Info, NotificationChannel.Gameplay, false, false, false, 5f,
                    "notif.pot_w01",
                    "Vaso irrigato +{delta}%",
                    "Pot watered +{delta}%",
                    "Idratazione del vaso aumentata.\nL'irrigazione mantiene la pianta in salute."),
                Spec("POT-F01", NotificationCategory.Pot, NotificationSeverity.Info, NotificationChannel.Gameplay, false, false, false, 5f,
                    "notif.pot_f01",
                    "Fertilizzante aggiunto +{delta}%",
                    "Fertilizer added +{delta}%",
                    "Fertilizzante applicato al vaso.\nMantieni il fertilizzante in range per una crescita ottimale."),
                Spec("PLT-ACT", NotificationCategory.Pot, NotificationSeverity.Info, NotificationChannel.Gameplay, false, false, false, 3f,
                    "notif.plt_act",
                    "{plantName}: {actionName} — {details}",
                    "{plantName}: {actionName} — {details}",
                    "Azione sul vaso eseguita.\nControlla i dettagli per l'esito (crescita, pH, stress)."),
                Spec("PLT-ARCTIC-TENSION-ON", NotificationCategory.Pot, NotificationSeverity.Warning, NotificationChannel.Gameplay, false, false, false, 6f,
                    "notif.plt_arctic_tension_on",
                    "Tensione Arctic Hask ({hask} esemplari) — penalità al raccolto fino a {pressure}%",
                    "Arctic Hask roster tension ({hask} specimens) — harvest penalty up to {pressure}%",
                    "Almeno due Arctic Hask nella Dome con pH fuori banda Neutra.\nLe altre specie subiscono penalità al raccolto fino al rientro in neutro o al ridurre gli Hask."),
                Spec("PLT-ARCTIC-TENSION-OFF", NotificationCategory.Pot, NotificationSeverity.Info, NotificationChannel.Gameplay, false, false, false, 6f,
                    "notif.plt_arctic_tension_off",
                    "Tensione Arctic Hask rientrata",
                    "Arctic Hask roster tension cleared",
                    "La tensione da stack Arctic Hask non è più attiva (pH neutro o meno di due esemplari).\nLe penalità al raccolto sulle altre piante non si applicano."),

                // ===== POT AUTOMATION (Terminal V3) =====
                Spec("POT-AUTO-INPROGRESS", NotificationCategory.Pot, NotificationSeverity.Warning, NotificationChannel.Gameplay, false, false, false, 1f,
                    "notif.pot_auto_inprogress",
                    "{message}",
                    "{message}",
                    "Automazione POT in corso.\nLe azioni programmate vengono eseguite sul vaso."),
                Spec("POT-AUTO-SUCCESS", NotificationCategory.Pot, NotificationSeverity.Success, NotificationChannel.Gameplay, false, false, false, 0f,
                    "notif.pot_auto_success",
                    "{message}",
                    "{message}",
                    "Automazione completata con successo.\nLe azioni configurate sono state applicate."),
                Spec("POT-AUTO-ERROR", NotificationCategory.Pot, NotificationSeverity.Danger, NotificationChannel.Gameplay, false, false, false, 0f,
                    "notif.pot_auto_error",
                    "{message}",
                    "{message}",
                    "Errore durante l'automazione.\nVerifica risorse, stato del vaso e riprova."),

                // ===== COMPAT: codici già usati in-game oggi (migrazione graduale, non rompe nulla) =====
                Spec("STAGE-UP-001", NotificationCategory.Pot, NotificationSeverity.Success, NotificationChannel.Gameplay, false, false, false, 0f,
                    "notif.stage_up",
                    "Cambio stadio: {potId} → {stage}",
                    "Stage up: {potId} → {stage}",
                    "La pianta è passata allo stadio successivo.\nOgni stadio ha requisiti diversi (acqua, luce, pH)."),
                Spec("CND-002", NotificationCategory.Pot, NotificationSeverity.Info, NotificationChannel.Gameplay, false, false, false, 0f,
                    "notif.cnd_002",
                    "Condizione migliorata: {details}",
                    "Condition improved: {details}",
                    "La condizione della pianta è migliorata.\nContinua a fornire acqua, luce e pH adeguati."),
                Spec("CND-001", NotificationCategory.Pot, NotificationSeverity.Warning, NotificationChannel.Gameplay, false, false, false, 0f,
                    "notif.cnd_001",
                    "Condizione peggiorata: {details}",
                    "Condition degraded: {details}",
                    "La condizione della pianta è peggiorata.\nControlla irrigazione, LED, pH e fertilizzante."),

                // Pot actions (legacy codes currently emitted by PotNotifications) — template passthrough
                Spec("POT-WATER-SUCCESS", NotificationCategory.Pot, NotificationSeverity.Success, NotificationChannel.Gameplay, false, false, false, 0f,
                    "notif.pot_water_success",
                    "{message}",
                    "{message}",
                    "Azione annaffiatura completata sul vaso.\nL'idratazione è stata aggiornata."),
                Spec("POT-LIGHT-SUCCESS", NotificationCategory.Pot, NotificationSeverity.Success, NotificationChannel.Gameplay, false, false, false, 0f,
                    "notif.pot_light_success",
                    "{message}",
                    "{message}",
                    "LED regolato con successo.\nLa luce influenza crescita e stress della pianta."),
                Spec("POT-PLANT-SUCCESS", NotificationCategory.Pot, NotificationSeverity.Success, NotificationChannel.Gameplay, false, false, false, 0f,
                    "notif.pot_plant_success",
                    "{message}",
                    "{message}",
                    "Operazione di semina completata.\nLa pianta è nel vaso e inizia a crescere."),
                Spec("POT-FERTILIZE-SUCCESS", NotificationCategory.Pot, NotificationSeverity.Success, NotificationChannel.Gameplay, false, false, false, 0f,
                    "notif.pot_fertilize_success",
                    "{message}",
                    "{message}",
                    "Fertilizzante applicato con successo.\nMantieni il range per una crescita ottimale."),
                Spec("POT-HARVEST-SUCCESS", NotificationCategory.Pot, NotificationSeverity.Success, NotificationChannel.Gameplay, false, false, false, 0f,
                    "notif.pot_harvest_success",
                    "{message}",
                    "{message}",
                    "Raccolto completato.\nIl prodotto è nell'inventario."),
                Spec("POT-SPRAY-SUCCESS", NotificationCategory.Pot, NotificationSeverity.Success, NotificationChannel.Gameplay, false, false, false, 0f,
                    "notif.pot_spray_success",
                    "{message}",
                    "{message}",
                    "Spray applicato con successo.\nInfluenza pH e rischio muffe."),
                Spec("POT-UPROOT-SUCCESS", NotificationCategory.Pot, NotificationSeverity.Success, NotificationChannel.Gameplay, false, false, false, 0f,
                    "notif.pot_uproot_success",
                    "{message}",
                    "{message}",
                    "Pianta sradicata dal vaso.\nIl vaso è libero per una nuova semina."),
                Spec("POT-ACTION-SUCCESS", NotificationCategory.Pot, NotificationSeverity.Success, NotificationChannel.Gameplay, false, false, false, 0f,
                    "notif.pot_action_success",
                    "{message}",
                    "{message}",
                    "Azione sul vaso completata.\nControlla lo stato della pianta."),

                Spec("POT-WATER-FAILED", NotificationCategory.Pot, NotificationSeverity.Danger, NotificationChannel.Gameplay, false, false, false, 0f,
                    "notif.pot_water_failed",
                    "{message}",
                    "{message}",
                    "Annaffiatura fallita.\nVerifica risorse (acqua) e stato del vaso."),
                Spec("POT-LIGHT-FAILED", NotificationCategory.Pot, NotificationSeverity.Danger, NotificationChannel.Gameplay, false, false, false, 0f,
                    "notif.pot_light_failed",
                    "{message}",
                    "{message}",
                    "Impostazione LED fallita.\nVerifica CRY e compatibilità della pianta con il LED."),
                Spec("POT-PLANT-FAILED", NotificationCategory.Pot, NotificationSeverity.Danger, NotificationChannel.Gameplay, false, false, false, 0f,
                    "notif.pot_plant_failed",
                    "{message}",
                    "{message}",
                    "Semina fallita.\nVerifica di avere un seme e che il vaso sia vuoto."),
                Spec("POT-FERTILIZE-FAILED", NotificationCategory.Pot, NotificationSeverity.Danger, NotificationChannel.Gameplay, false, false, false, 0f,
                    "notif.pot_fertilize_failed",
                    "{message}",
                    "{message}",
                    "Fertilizzazione fallita.\nVerifica di avere fertilizzante e che il vaso sia valido."),
                Spec("POT-HARVEST-FAILED", NotificationCategory.Pot, NotificationSeverity.Danger, NotificationChannel.Gameplay, false, false, false, 0f,
                    "notif.pot_harvest_failed",
                    "{message}",
                    "{message}",
                    "Raccolto fallito.\nLa pianta potrebbe non essere allo stadio giusto o mancare requisiti."),
                Spec("POT-SPRAY-FAILED", NotificationCategory.Pot, NotificationSeverity.Danger, NotificationChannel.Gameplay, false, false, false, 0f,
                    "notif.pot_spray_failed",
                    "{message}",
                    "{message}",
                    "Spray fallito.\nVerifica di avere l'additivo in inventario."),
                Spec("POT-UPROOT-FAILED", NotificationCategory.Pot, NotificationSeverity.Danger, NotificationChannel.Gameplay, false, false, false, 0f,
                    "notif.pot_uproot_failed",
                    "{message}",
                    "{message}",
                    "Sradicamento fallito.\nVerifica che il vaso abbia una pianta da rimuovere."),
                Spec("POT-ACTION-FAILED", NotificationCategory.Pot, NotificationSeverity.Danger, NotificationChannel.Gameplay, false, false, false, 0f,
                    "notif.pot_action_failed",
                    "{message}",
                    "{message}",
                    "Azione sul vaso fallita.\nControlla risorse e requisiti della pianta."),
                Spec("PH-COUNTDOWN-001", NotificationCategory.Ph, NotificationSeverity.Warning, NotificationChannel.Gameplay, true, false, true, 2f,
                    "warn.ph_countdown",
                    "⚠️ {plant} tra {days} giorni morirà (pH estremo).",
                    "⚠️ {plant} will die in {days} days (extreme pH).",
                    "La pianta è in zona pH pericolosa.\nRegola il pH della Dome (additivi, spray) per salvarla."),
                Spec("PH-DEATH-001", NotificationCategory.Ph, NotificationSeverity.Danger, NotificationChannel.Gameplay, false, false, false, 0f,
                    "danger.ph_death",
                    "🚨 {plant} morta per pH estremo!",
                    "🚨 {plant} died from extreme pH!",
                    "La pianta è morta a causa del pH fuori range.\nMonitora il pH della Dome per le prossime piante."),
                Spec("PLANT-DEATH-001", NotificationCategory.Pot, NotificationSeverity.Danger, NotificationChannel.Gameplay, false, false, false, 0f,
                    "danger.plant_death",
                    "🚨 Pianta morta! {reason}",
                    "🚨 Plant died! {reason}",
                    "La pianta è morta per la causa indicata.\nRimuovila e pianta di nuovo se necessario."),
                Spec("WATER-001", NotificationCategory.Ecosystem, NotificationSeverity.Info, NotificationChannel.Gameplay, false, false, false, 2f,
                    "notif.water_001",
                    "Raccolta acqua piovana: {amount}",
                    "Collected rainwater: {amount}",
                    "Acqua piovana raccolta dal sistema.\nUsala per irrigazione e potabilizzazione."),

                // ===== CONDENSATION SYSTEM (FASE 11) =====
                Spec("COND-001", NotificationCategory.Ecosystem, NotificationSeverity.Info, NotificationChannel.Gameplay, false, false, false, 5f,
                    "notif.cond_001",
                    "💧 Raccolta condensazione disponibile ({percentage}%)",
                    "💧 Condensation collection available ({percentage}%)",
                    "Puoi raccogliere acqua dalla condensazione.\nUsa il sistema di raccolta per ottenere WAT-RAW."),
                Spec("COND-002", NotificationCategory.Ecosystem, NotificationSeverity.Warning, NotificationChannel.Gameplay, false, false, false, 10f,
                    "notif.cond_002",
                    "⚠️ Limite condensazione raggiunto (100%)",
                    "⚠️ Condensation cap reached (100%)",
                    "Il serbatoio di condensazione è pieno.\nRaccogli l'acqua per evitare perdite e ridurre umidità."),
                Spec("COND-003", NotificationCategory.Ecosystem, NotificationSeverity.Info, NotificationChannel.Gameplay, false, false, false, 5f,
                    "notif.cond_003",
                    "Condensazione azzerata - nessuna produzione",
                    "Condensation reset - no production",
                    "La condensazione è stata azzerata (es. cambio stanza o reset).\nRiavvierà con la prossima attività."),
                Spec("COND-004", NotificationCategory.Ecosystem, NotificationSeverity.Success, NotificationChannel.Gameplay, false, false, false, 3f,
                    "notif.cond_004",
                    "✨ Potenziamento LED attivo: +2 WAT-RAW",
                    "✨ LED boost active: +2 WAT-RAW",
                    "Il potenziamento LED aumenta la produzione di acqua dalla condensazione.\nEffetto temporaneo: sfruttalo per accumulare WAT-RAW."),
                Spec("COND-005", NotificationCategory.Ecosystem, NotificationSeverity.Warning, NotificationChannel.Gameplay, true, false, true, 15f,
                    "warn.cond_005",
                    "⚠️ Serbatoio a metà",
                    "⚠️ Tank half full",
                    "Il serbatoio di condensazione è a metà.\nRaccogli presto per evitare sovraccarico e muffe."),
                Spec("COND-006", NotificationCategory.Ecosystem, NotificationSeverity.Warning, NotificationChannel.Gameplay, true, false, true, 15f,
                    "warn.cond_006",
                    "⚠️ Umidità impatta muffe",
                    "⚠️ Humidity affects mold",
                    "L'umidità alta favorisce le muffe.\nVentila o riduci irrigazione per tenere sotto controllo il rischio."),
                Spec("COND-007", NotificationCategory.Ecosystem, NotificationSeverity.Danger, NotificationChannel.Gameplay, true, false, true, 10f,
                    "danger.cond_007",
                    "🚨 Condensazione 90% - Rischio critico muffe",
                    "🚨 Condensation 90% - Critical mold risk",
                    "Condensazione e umidità molto alte: rischio muffe critico.\nRaccogli acqua e ventila subito."),
                Spec("COND-008", NotificationCategory.Ecosystem, NotificationSeverity.Danger, NotificationChannel.Gameplay, true, false, true, 5f,
                    "danger.cond_008",
                    "🚨 Serbatoio pieno, umidità alta",
                    "🚨 Tank full, high humidity",
                    "Serbatoio pieno e umidità elevata.\nRaccogli l'acqua e apri la ventilazione per evitare muffe."),
                Spec("SPORE-001", NotificationCategory.Inventory, NotificationSeverity.Info, NotificationChannel.Gameplay, false, false, false, 2f,
                    "notif.spore_001",
                    "Ottenute spore!",
                    "You got a spore!",
                    "Hai ottenuto una spora (es. da raccolto o lab).\nUsala per semina o ricerca nel Lab."),
                Spec("INV-FRUIT-001", NotificationCategory.Inventory, NotificationSeverity.Info, NotificationChannel.Gameplay, false, false, false, 2f,
                    "notif.inv_fruit_001",
                    "Nuovo frutto aggiunto all'inventario: {amount}",
                    "New fruit added to Inventory: {amount}",
                    "Frutto raccolto e aggiunto all'inventario.\nConsumalo per idratazione o vendilo al Mercato."),
                Spec("LGT-001", NotificationCategory.System, NotificationSeverity.Info, NotificationChannel.Gameplay, false, false, false, 2f,
                    "notif.lgt_001",
                    "{message}",
                    "{message}",
                    "Messaggio generico sul sistema LED.\nControlla la Dome o i vasi per dettagli."),
                Spec("LGT-002", NotificationCategory.System, NotificationSeverity.Danger, NotificationChannel.Gameplay, false, false, false, 5f,
                    "notif.lgt_002",
                    "{message}",
                    "{message}",
                    "L'irrigazione è disattivata su questo vaso.\nAttivala dal terminale POT per evitare disidratazione e blocco della crescita."),
                Spec("LGT-003", NotificationCategory.System, NotificationSeverity.Info, NotificationChannel.Gameplay, false, false, false, 2f,
                    "notif.lgt_003",
                    "{message}",
                    "{message}",
                    "Informazione sul LED (es. stato o impostazione).\nVedi il messaggio per il dettaglio."),
                Spec("LGT-004", NotificationCategory.System, NotificationSeverity.Info, NotificationChannel.Gameplay, false, false, false, 2f,
                    "notif.lgt_004",
                    "{message}",
                    "{message}",
                    "Informazione sul sistema luce.\nControlla Dome o pannello LED per azioni."),

                // ===== VISITORS =====
                Spec("VIS-001", NotificationCategory.System, NotificationSeverity.Info, NotificationChannel.Gameplay, true, false, true, 0f,
                    "notif.vis_001",
                    "Visitatore in attesa",
                    "Visitor waiting for player!",
                    "Un visitatore è in attesa.\nVai alla posizione indicata per interagire."),

                // ===== INVENTORY =====
                Spec("INV-000", NotificationCategory.Inventory, NotificationSeverity.Info, NotificationChannel.Gameplay, false, false, false, 10f,
                    "notif.inv000",
                    "Inventario aperto",
                    "Inventory accessed",
                    "Hai aperto l'inventario.\nQui vedi oggetti, semi, frutti e risorse."),
                Spec("ITEM-GET", NotificationCategory.Inventory, NotificationSeverity.Info, NotificationChannel.Gameplay, false, true, false, 1f,
                    "notif.item_get",
                    "Ottenuto da {location}",
                    "Obtained from {location}",
                    "Hai ottenuto un oggetto dalla posizione indicata.\nControlla l'inventario per vederlo."),
                Spec("ADDED-TO-INVENTORY", NotificationCategory.Inventory, NotificationSeverity.Success, NotificationChannel.Gameplay, false, true, false, 1f,
                    "notif.added_to_inventory",
                    "+{quantity} {itemName} — {room}",
                    "+{quantity} {itemName} — {room}",
                    "Oggetto aggiunto all'inventario dalla stanza indicata.\nUsa l'inventario per gestire le risorse."),
                Spec("INV-REM", NotificationCategory.Inventory, NotificationSeverity.Info, NotificationChannel.Gameplay, false, false, false, 2f,
                    "notif.inv_rem",
                    "Rimosso dall’inventario: {item} {delta}",
                    "Removed from Inventory: {item} {delta}",
                    "Un oggetto è stato rimosso dall'inventario (uso, vendita o altro).\nIl delta indica la variazione."),
                Spec("INV-DET-WARN", NotificationCategory.Inventory, NotificationSeverity.Warning, NotificationChannel.Gameplay, false, false, false, 12f,
                    "notif.inv_det_warn",
                    "⚠️ Inventario: {n} item organici hanno perso qualità (deperimento).",
                    "⚠️ Inventory: {n} organic item(s) lost quality (deterioration).",
                    "Passaggio al nuovo giorno: piante, frutti, semi, spore e cibi sintetici in borsa perdono 1 punto qualità se non conservati.\nControlla l'inventario, Seed Storage o Dispensa."),
                Spec("INV-DET-ORG", NotificationCategory.Inventory, NotificationSeverity.Warning, NotificationChannel.Gameplay, false, false, false, 6f,
                    "notif.inv_det_org",
                    "🧪 {n} item deperiti → Residui organici",
                    "🧪 {n} item(s) spoiled → Organic residue",
                    "La qualità di alcuni item organici è arrivata a zero: sono stati convertiti in Residui organici.\nUsa i residui nel Lab o smaltisci secondo le regole della Cupola."),
                Spec("INV-DET-PROT", NotificationCategory.Inventory, NotificationSeverity.Warning, NotificationChannel.Gameplay, false, false, false, 6f,
                    "notif.inv_det_prot",
                    "🧪 {n} carne sintetica deperita → Residui proteici",
                    "🧪 {n} synthetic meat spoiled → Protein residue",
                    "La carne sintetica in inventario ha perso tutta la conservabilità: è diventata Residui proteici.\nUsali come input nel Lab dove richiesto."),
                Spec("HYD-001", NotificationCategory.Player, NotificationSeverity.Info, NotificationChannel.Gameplay, false, false, false, 15f,
                    "notif.hyd001",
                    "Hai bevuto: Idratazione +{deltaHyd}% — +{deltaAct} Azione",
                    "You drank: Hydration +{deltaHyd}% — +{deltaAct} Action",
                    "Hai consumato una bevanda: recuperi idratazione e punti azione.\nUtile per continuare le attività."),

                // ===== DIARY / RESEARCH / WIKI =====
                Spec("SPORAE-001", NotificationCategory.Diary, NotificationSeverity.Info, NotificationChannel.Gameplay, false, false, false, 15f,
                    "notif.sporae001",
                    "Diario SPORAE aperto",
                    "SPORAE Diary accessed",
                    "Hai aperto il Diario SPORAE.\nQui trovi annotazioni e progressi della storia."),
                Spec("RES-001", NotificationCategory.Research, NotificationSeverity.Info, NotificationChannel.Gameplay, false, false, false, 0f,
                    "notif.res001",
                    "Ricerca avviata: {nodeTitle}",
                    "Research started: {nodeTitle}",
                    "Una ricerca è stata avviata nel Lab.\nAttendi il completamento per sbloccare nuovi contenuti."),
                Spec("WIKI-UNLOCK", NotificationCategory.Wiki, NotificationSeverity.Success, NotificationChannel.Gameplay, false, false, false, 0f,
                    "notif.wiki_unlock",
                    "{plantType} aggiunta alla Wiki (piante)",
                    "{plantType} added to WIKI PLANTS",
                    "Una nuova varietà è stata aggiunta alla Wiki Piante.\nConsulta la Wiki per dati e consigli."),
                Spec("RES-UNLOCK", NotificationCategory.Research, NotificationSeverity.Success, NotificationChannel.Gameplay, false, false, false, 0f,
                    "notif.res_unlock",
                    "Specie individuale sbloccata per studio",
                    "Individual species unlocked for study",
                    "Una specie è ora disponibile per la ricerca nel Lab.\nUsa il Lab per studiarla e sbloccare bonus."),

                // ===== REPUTATION =====
                Spec("REP-CHANGE", NotificationCategory.Reputation, NotificationSeverity.Info, NotificationChannel.Gameplay, false, false, false, 5f,
                    "notif.rep_change",
                    "Reputazione ({faction}): {delta}",
                    "{faction} reputation {delta}",
                    "La reputazione con la fazione indicata è cambiata.\nAlta reputazione sblocca dialoghi e offerte."),

                // ===== WATCHERS: DANGER PERSISTENTI / WARNINGS =====
                Spec("PH-ULTRA-ACID", NotificationCategory.Ph, NotificationSeverity.Danger, NotificationChannel.Gameplay, true, false, true, 0f,
                    "danger.ph_ultra_acid",
                    "pH ULTRA ACIDO rilevato ({ph}). Stabilizzare subito.",
                    "ULTRA ACID pH detected ({ph}). Stabilize immediately.",
                    "Il pH della Dome è sceso sotto la soglia acida.\nUsa additivi basici o spray per riportare il valore verso il neutro."),
                Spec("PH-ULTRA-BASIC", NotificationCategory.Ph, NotificationSeverity.Danger, NotificationChannel.Gameplay, true, false, true, 0f,
                    "danger.ph_ultra_basic",
                    "pH ULTRA BASICO rilevato ({ph}). Stabilizzare subito.",
                    "ULTRA BASIC pH detected ({ph}). Stabilize immediately.",
                    "Il pH della Dome ha superato la soglia basica.\nUsa additivi acidi per riportare il valore verso il neutro."),
                Spec("PH-003", NotificationCategory.Ph, NotificationSeverity.Warning, NotificationChannel.Gameplay, true, false, true, 5f,
                    "warn.ph_unstable",
                    "pH della Cupola instabile ({ph})",
                    "Dome pH unstable ({ph})",
                    "Il pH della Cupola oscilla rispetto al range sicuro.\nUsa stabilizzatori o additivi per riportarlo verso il neutro."),
                Spec("PH-RISK-COUNTDOWN", NotificationCategory.Ph, NotificationSeverity.Warning, NotificationChannel.Gameplay, true, false, true, 2f,
                    "warn.ph_risk_countdown",
                    "⚠️ {potId}: {plant} rischia la morte in {days} giorni (pH estremo).",
                    "⚠️ {potId}: {plant} may die in {days} days (extreme pH).",
                    "La pianta è in una zona di pH pericolosa per la sua famiglia.\nRegola il pH della Dome (additivi, piante) o sposta la pianta per evitare la morte."),

                Spec("WAT-OVR-WARN", NotificationCategory.Water, NotificationSeverity.Warning, NotificationChannel.Gameplay, true, false, true, 5f,
                    "warn.water_over",
                    "⚠️ Irrigazione eccessiva su {potId} ({pct}%). Rischio muffe.",
                    "⚠️ Overwatering on {potId} ({pct}%). Mold risk.",
                    "Il vaso è troppo bagnato: aumenta il rischio muffe.\nRiduci l'irrigazione e ventila la Dome."),
                Spec("WAT-OVR-DANGER", NotificationCategory.Water, NotificationSeverity.Danger, NotificationChannel.Gameplay, true, false, true, 0f,
                    "danger.water_over",
                    "🚨 Irrigazione eccessiva persistente su {potId} ({days} giorni).",
                    "🚨 Persistent overwatering on {potId} ({days} days).",
                    "Irrigazione eccessiva da giorni: la pianta e il vaso sono a rischio.\nSospendi l'acqua e controlla le muffe."),

                Spec("LGT-STR-100", NotificationCategory.Light, NotificationSeverity.Danger, NotificationChannel.Gameplay, true, false, true, 0f,
                    "danger.light_stress_100",
                    "🚨 Stress luminoso al 100% su {potId}. Regola il LED.",
                    "🚨 Light stress 100% on {potId}. Adjust LED.",
                    "Il LED è rimasto acceso troppo a lungo per questa pianta.\nSpegni o cambia colore (Blu/Rosso) dal terminale POT per ridurre lo stress."),

                Spec("FRT-MISSING-BLOCK", NotificationCategory.Fertilizer, NotificationSeverity.Danger, NotificationChannel.Gameplay, true, false, true, 0f,
                    "danger.fertilizer_missing",
                    "🚨 {potId}: fertilizzante mancante. Crescita bloccata.",
                    "🚨 {potId}: fertilizer missing. Growth blocked.",
                    "Il vaso non ha fertilizzante: la crescita è bloccata.\nAggiungi fertilizzante dal Lab o dall'inventario."),
                Spec("FRT-OUT-RANGE", NotificationCategory.Fertilizer, NotificationSeverity.Warning, NotificationChannel.Gameplay, true, false, true, 10f,
                    "warn.fertilizer_out_range",
                    "⚠️ Fertilizzante fuori range su {potId}. Crescita rallentata.",
                    "⚠️ Fertilizer out of range on {potId}. Growth slowed.",
                    "Il livello di fertilizzante non è nel range ottimale.\nRegola la dose per una crescita migliore."),

                // Mold level gained/reduced (one toast per level, with cause for reductions)
                Spec("MOLD-GAIN", NotificationCategory.Mold, NotificationSeverity.Warning, NotificationChannel.Gameplay, false, false, false, 0f,
                    "warn.mold_gain",
                    "⚠️ Muffa Lv{level} in {potId}",
                    "⚠️ Mold Lv{level} on {potId}",
                    "Il rischio muffe è aumentato a livello {level}.\nRiduci l'irrigazione, ventila e monitora l'irrigazione eccessiva."),
                Spec("MOLD-REDUCE", NotificationCategory.Mold, NotificationSeverity.Info, NotificationChannel.Gameplay, false, false, false, 0f,
                    "notif.mold_reduce",
                    "✅ Muffa ridotta su {potId} — {cause}",
                    "✅ Mold reduced on {potId} — {cause}",
                    "Il livello muffa è sceso di 1.\nCausa: {cause}. Continua a monitorare per evitare recidive."),

                Spec("MLD-RISK-CRIT", NotificationCategory.Mold, NotificationSeverity.Danger, NotificationChannel.Gameplay, true, false, true, 0f,
                    "danger.mold_crit",
                    "🚨 Rischio muffe CRITICO su {potId}.",
                    "🚨 CRITICAL mold risk on {potId}.",
                    "Rischio muffe critico sul vaso: agisci subito.\nRiduci umidità, ventila e usa spray se disponibile."),
                Spec("MLD-INFESTED", NotificationCategory.Mold, NotificationSeverity.Danger, NotificationChannel.Gameplay, false, false, false, 0f,
                    "danger.mold_infested",
                    "🚨 Infestazione muffe su {potId} — livello -{levelLost}",
                    "🚨 Mold infestation on {potId} — level -{levelLost}",
                    "Il vaso è infestato dalle muffe.\nLa pianta ha perso {levelLost} livello/i. Tratta con spray antimuffa e migliora ventilazione."),
                Spec("MLD-INFESTED-CLEARED", NotificationCategory.Mold, NotificationSeverity.Info, NotificationChannel.Gameplay, false, false, false, 0f,
                    "notif.mold_infested_cleared",
                    "✅ Infestazione rimossa su {potId}",
                    "✅ Mold infestation cleared on {potId}",
                    "L'infestazione muffe è rientrata.\nMonitora il rischio muffe per evitare recidive."),
                Spec("MLD-201", NotificationCategory.Mold, NotificationSeverity.Danger, NotificationChannel.Gameplay, true, false, true, 0f,
                    "danger.mld201",
                    "Muffa rilevata in {potId}",
                    "Mold detected in {potId}",
                    "Muffa rilevata nel vaso.\nMonitora e tratta per evitare che si diffonda."),

                // ===== PLANT LEVEL / STERILE / BURN EVENTS =====
                Spec("PLT-LVL-UP", NotificationCategory.Pot, NotificationSeverity.Success, NotificationChannel.Gameplay, false, false, false, 0f,
                    "notif.plt_lvl_up",
                    "⬆️ {potId}: {plantCode} salita a Livello {level}!",
                    "⬆️ {potId}: {plantCode} reached Level {level}!",
                    "La pianta ha completato abbastanza cicli e ha guadagnato un livello.\nI poteri attivi e passivi scalano con il livello."),
                Spec("PLT-LVL-DOWN", NotificationCategory.Pot, NotificationSeverity.Warning, NotificationChannel.Gameplay, false, false, false, 0f,
                    "warn.plt_lvl_down",
                    "⬇️ {potId}: {plantCode} perso Livello {oldLevel} → {newLevel} ({reason})",
                    "⬇️ {potId}: {plantCode} lost Level {oldLevel} → {newLevel} ({reason})",
                    "La pianta ha perso un livello a causa di stress estremo o infestazione.\nMigliora le condizioni per evitare ulteriori regressioni."),
                Spec("BURN-STAGE-REGRESS", NotificationCategory.Pot, NotificationSeverity.Danger, NotificationChannel.Gameplay, false, false, false, 0f,
                    "danger.burn_stage_regress",
                    "🔥 {potId}: Regressione stadio {oldStage} → {newStage} (stress da bruciatura)",
                    "🔥 {potId}: Stage regression {oldStage} → {newStage} (Burn Stress)",
                    "Lo stress da bruciatura prolungato ha causato la regressione della pianta allo stadio precedente.\nSpegni o cambia il LED dal terminale POT."),
                Spec("STERILE-001", NotificationCategory.Pot, NotificationSeverity.Warning, NotificationChannel.Gameplay, false, false, false, 0f,
                    "warn.sterile_on",
                    "⚠️ {potId}: {plantCode} sterile (pH Ultra Basico)",
                    "⚠️ {potId}: {plantCode} sterile (Ultra Basic pH)",
                    "La pianta Pure è entrata in stato sterile.\nIn pH Ultra Basico le piante Pure non producono nuovi frutti.\nRipristina il pH verso il neutro per rimuovere la sterilità."),
                Spec("STERILE-CLEARED", NotificationCategory.Pot, NotificationSeverity.Info, NotificationChannel.Gameplay, false, false, false, 0f,
                    "notif.sterile_off",
                    "✅ {potId}: {plantCode} non più sterile",
                    "✅ {potId}: {plantCode} sterility cleared",
                    "La pianta ha recuperato la fertilità.\nIl pH è rientrato dalla zona Ultra Basica."),
                Spec("PLT-HYB-PLANTED", NotificationCategory.Pot, NotificationSeverity.Success, NotificationChannel.Gameplay, false, false, false, 3f,
                    "notif.plt_hyb_planted",
                    "🌱 {potId}: seme con origine Lab piantato ({displayName}, {plantCode})",
                    "🌱 {potId}: Lab-origin seed planted ({displayName}, {plantCode})",
                    "Provenienza incrocio: {lineage}\nIl profilo seme/vaso è persistito nel salvataggio."),

                // ===== LORE TOPICS (starter) =====
                Spec("LOR-VLT-001", NotificationCategory.Lore, NotificationSeverity.Info, NotificationChannel.Lore, false, false, false, 90f,
                    "lore.vlt.001",
                    "📡 Telemetria: variazioni microclima nei condotti.",
                    "📡 Telemetry: microclimate fluctuation in ventilation ducts.",
                    "Frammento di lore sulla Vault: i condotti mostrano anomalie.\nEsplora per scoprire di più sulla struttura."),
                Spec("LOR-ECO-001", NotificationCategory.Lore, NotificationSeverity.Info, NotificationChannel.Lore, false, false, false, 90f,
                    "lore.eco.001",
                    "Le spore reagiscono al pH come se ricordassero qualcosa.",
                    "Spores react to pH as if they remember something.",
                    "Nota di lore sull'ecosistema: le spore sembrano \"ricordare\" il pH.\nCollega ricerca e narrativa."),
                Spec("LOR-MKT-001", NotificationCategory.Lore, NotificationSeverity.Info, NotificationChannel.Lore, false, false, false, 120f,
                    "lore.mkt.001",
                    "Sussurri: \"qualcuno paga bene per semi Pure… senza domande\".",
                    "Whispers: \"someone pays well for Pure seeds… no questions\".",
                    "Indizio di lore sul Mercato: traffico di semi Pure.\nEsplora il Mercato per la storia."),
            };

            // Per rispettare “39 tipologie”, aggiungiamo placeholder per codici ancora non implementati a call-site:
            // - Questi non rompono nulla: servono solo per debug console/push manuale.
            // (Puoi estendere qui con altri topic e codici in modo data-driven).

            return list;
        }

        private static NotificationTypeSpec Spec(
            string code,
            NotificationCategory category,
            NotificationSeverity severity,
            NotificationChannel channel,
            bool dangerPersistent,
            bool isItem,
            bool isStateDriven,
            float cooldown,
            string locKey,
            string it,
            string en,
            string tooltipIt = null,
            string tooltipEn = null)
        {
            return new NotificationTypeSpec
            {
                Code = code,
                Category = category,
                DefaultSeverity = severity,
                Channel = channel,
                IsDangerPersistent = dangerPersistent,
                IsItemLayout = isItem,
                IsStateDriven = isStateDriven,
                CooldownSeconds = cooldown,
                LocKey = locKey,
                TemplateIt = it,
                TemplateEn = en,
                TooltipIt = tooltipIt,
                // Se manca TooltipEn ma c'è un tooltip IT, usa il template EN (titolo) così in inglese non si fa fallback sul paragrafo italiano.
                TooltipEn = !string.IsNullOrEmpty(tooltipEn)
                    ? tooltipEn
                    : (!string.IsNullOrEmpty(tooltipIt) ? en : null)
            };
        }
    }
}


