using System.Collections.Generic;

namespace Sporae.UI.UIToolkit.NotificationsFoundation
{
    /// <summary>
    /// Default TypeSpec list (ex novo) — usata se non esiste un asset Registry in Resources.
    /// </summary>
    public static class NotificationTypeSpecDefaults
    {
        public static IReadOnlyList<NotificationTypeSpec> BuildDefaults()
        {
            // NOTE: templates sono localizzati IT/EN. Parametri via {token}.
            // NOTE: Cooldown suggeriti sono conservativi per evitare spam.

            var list = new List<NotificationTypeSpec>
            {
                // ===== AUTOMATICHE / ECOSYSTEM =====
                Spec("SYS-100", NotificationCategory.System, NotificationSeverity.Info, NotificationChannel.Gameplay, false, false, false, 30f,
                    "notif.sys100",
                    "Sistema di condensazione ottimale",
                    "Condensation system optimal"),

                Spec("ACT-050", NotificationCategory.Actions, NotificationSeverity.Warning, NotificationChannel.Gameplay, false, false, true, 20f,
                    "notif.act050",
                    "Punti azione bassi",
                    "Low action points"),

                Spec("CRY-777", NotificationCategory.Economy, NotificationSeverity.Info, NotificationChannel.Gameplay, false, false, false, 3f,
                    "notif.cry777",
                    "Scambio completato {delta} CRY",
                    "Trade completed {delta} CRY"),

                // ===== TOPBAR =====
                Spec("SYS-001", NotificationCategory.TopBar, NotificationSeverity.Info, NotificationChannel.Gameplay, false, false, false, 10f,
                    "notif.sys001",
                    "Database WIKI aperto",
                    "Wiki database accessed"),
                Spec("SYS-002", NotificationCategory.TopBar, NotificationSeverity.Info, NotificationChannel.Gameplay, false, false, false, 10f,
                    "notif.sys002",
                    "Pannello impostazioni aperto",
                    "Settings panel opened"),
                Spec("SYS-003", NotificationCategory.TopBar, NotificationSeverity.Success, NotificationChannel.Gameplay, false, false, false, 3f,
                    "notif.sys003",
                    "Gioco salvato correttamente",
                    "Game saved successfully"),
                Spec("SYS-999", NotificationCategory.TopBar, NotificationSeverity.Warning, NotificationChannel.Gameplay, false, false, false, 10f,
                    "notif.sys999",
                    "Uscita da SPORIUM...",
                    "Exiting SPORIUM..."),

                // ===== ROOMS =====
                Spec("PLT-101", NotificationCategory.Room, NotificationSeverity.Info, NotificationChannel.Gameplay, false, false, false, 8f,
                    "notif.plt101",
                    "Dati pianta consultati",
                    "Plant data accessed"),
                Spec("LAB-001", NotificationCategory.Room, NotificationSeverity.Info, NotificationChannel.Gameplay, false, false, false, 8f,
                    "notif.lab001",
                    "Laboratorio accesso effettuato",
                    "Laboratory accessed"),
                Spec("DOR-001", NotificationCategory.Room, NotificationSeverity.Info, NotificationChannel.Gameplay, false, false, false, 8f,
                    "notif.dor001",
                    "Dormitorio accesso effettuato",
                    "Dormitory accessed"),
                Spec("SEED-001", NotificationCategory.Room, NotificationSeverity.Info, NotificationChannel.Gameplay, false, false, false, 8f,
                    "notif.seed001",
                    "Archivio semi aperto",
                    "Seed Archive accessed"),
                Spec("KTCH-001", NotificationCategory.Room, NotificationSeverity.Info, NotificationChannel.Gameplay, false, false, false, 8f,
                    "notif.ktch001",
                    "Terminale cucina accesso effettuato",
                    "Kitchen Terminal accessed"),
                Spec("MKT-666", NotificationCategory.Room, NotificationSeverity.Warning, NotificationChannel.Gameplay, false, false, false, 8f,
                    "notif.mkt666",
                    "Ingresso al Mercato Nero...",
                    "Entering Black Market..."),

                // ===== LAB ACTIONS (codici univoci OK/FAIL) =====
                Spec("LAB-INC-OK", NotificationCategory.Lab, NotificationSeverity.Success, NotificationChannel.Gameplay, false, false, false, 0f,
                    "notif.lab_inc_ok",
                    "Incubazione riuscita!",
                    "Seed incubation successful!"),
                Spec("LAB-INC-FAIL", NotificationCategory.Lab, NotificationSeverity.Danger, NotificationChannel.Gameplay, false, false, false, 0f,
                    "notif.lab_inc_fail",
                    "Incubazione fallita. Seme scartato.",
                    "Incubation failed. Seed discarded."),
                Spec("LAB-GRF-OK", NotificationCategory.Lab, NotificationSeverity.Success, NotificationChannel.Gameplay, false, false, false, 0f,
                    "notif.lab_grf_ok",
                    "Graft riuscito! Creato {seedCode}",
                    "Graft successful! {seedCode} created"),
                Spec("LAB-GRF-FAIL", NotificationCategory.Lab, NotificationSeverity.Danger, NotificationChannel.Gameplay, false, false, false, 0f,
                    "notif.lab_grf_fail",
                    "Graft fallito. Residuo organico formato.",
                    "Graft failed. Organic residue formed."),
                Spec("INV-SPR", NotificationCategory.Inventory, NotificationSeverity.Info, NotificationChannel.Gameplay, false, false, false, 2f,
                    "notif.inv_spr",
                    "Raccolte {amount} spore",
                    "Collected {amount} spores"),
                Spec("LAB-MIC", NotificationCategory.Lab, NotificationSeverity.Info, NotificationChannel.Gameplay, false, false, false, 5f,
                    "notif.lab_mic",
                    "Microscopio caricato con {sporeCode}",
                    "Microscope loaded with {sporeCode}"),
                Spec("LAB-PIP", NotificationCategory.Lab, NotificationSeverity.Info, NotificationChannel.Gameplay, false, false, false, 5f,
                    "notif.lab_pip",
                    "Pipetta caricata con {sporeCode}",
                    "Pipette loaded with {sporeCode}"),

                // ===== POT / PLANT ACTIONS =====
                Spec("POT-PLANT-OK", NotificationCategory.Pot, NotificationSeverity.Success, NotificationChannel.Gameplay, false, false, false, 0f,
                    "notif.pot_plant_ok",
                    "{plantName} piantata con successo",
                    "{plantName} planted successfully"),
                Spec("POT-PLANT-IRR-OK", NotificationCategory.Pot, NotificationSeverity.Success, NotificationChannel.Gameplay, false, false, false, 0f,
                    "notif.pot_plant_irr_ok",
                    "{plantName} piantata e irrigata",
                    "{plantName} planted and irrigated"),
                Spec("POT-REMOVE", NotificationCategory.Pot, NotificationSeverity.Info, NotificationChannel.Gameplay, false, false, false, 1f,
                    "notif.pot_remove",
                    "Pianta rimossa dal vaso",
                    "Plant removed from pot"),
                Spec("POT-HARVEST-OK", NotificationCategory.Pot, NotificationSeverity.Success, NotificationChannel.Gameplay, false, false, false, 0f,
                    "notif.pot_harvest_ok",
                    "Raccolto ottenuto",
                    "Harvest collected"),
                Spec("POT-W01", NotificationCategory.Pot, NotificationSeverity.Info, NotificationChannel.Gameplay, false, false, false, 5f,
                    "notif.pot_w01",
                    "Vaso irrigato +{delta}%",
                    "Pot watered +{delta}%"),
                Spec("POT-F01", NotificationCategory.Pot, NotificationSeverity.Info, NotificationChannel.Gameplay, false, false, false, 5f,
                    "notif.pot_f01",
                    "Fertilizzante aggiunto +{delta}%",
                    "Fertilizer added +{delta}%"),
                Spec("PLT-ACT", NotificationCategory.Pot, NotificationSeverity.Info, NotificationChannel.Gameplay, false, false, false, 3f,
                    "notif.plt_act",
                    "{plantName} {actionName} — {details}",
                    "{plantName} {actionName} — {details}"),

                // ===== COMPAT: codici già usati in-game oggi (migrazione graduale, non rompe nulla) =====
                Spec("STAGE-UP-001", NotificationCategory.Pot, NotificationSeverity.Info, NotificationChannel.Gameplay, false, false, false, 0f,
                    "notif.stage_up",
                    "Stage up: {potId} → {stage}",
                    "Stage up: {potId} → {stage}"),
                Spec("CND-002", NotificationCategory.Pot, NotificationSeverity.Info, NotificationChannel.Gameplay, false, false, false, 0f,
                    "notif.cnd_002",
                    "Condizione migliorata: {details}",
                    "Condition improved: {details}"),
                Spec("CND-001", NotificationCategory.Pot, NotificationSeverity.Warning, NotificationChannel.Gameplay, false, false, false, 0f,
                    "notif.cnd_001",
                    "Condizione peggiorata: {details}",
                    "Condition degraded: {details}"),

                // Pot actions (legacy codes currently emitted by PotNotifications) — template passthrough
                Spec("POT-WATER-SUCCESS", NotificationCategory.Pot, NotificationSeverity.Success, NotificationChannel.Gameplay, false, false, false, 0f,
                    "notif.pot_water_success",
                    "{message}",
                    "{message}"),
                Spec("POT-LIGHT-SUCCESS", NotificationCategory.Pot, NotificationSeverity.Success, NotificationChannel.Gameplay, false, false, false, 0f,
                    "notif.pot_light_success",
                    "{message}",
                    "{message}"),
                Spec("POT-PLANT-SUCCESS", NotificationCategory.Pot, NotificationSeverity.Success, NotificationChannel.Gameplay, false, false, false, 0f,
                    "notif.pot_plant_success",
                    "{message}",
                    "{message}"),
                Spec("POT-FERTILIZE-SUCCESS", NotificationCategory.Pot, NotificationSeverity.Success, NotificationChannel.Gameplay, false, false, false, 0f,
                    "notif.pot_fertilize_success",
                    "{message}",
                    "{message}"),
                Spec("POT-HARVEST-SUCCESS", NotificationCategory.Pot, NotificationSeverity.Success, NotificationChannel.Gameplay, false, false, false, 0f,
                    "notif.pot_harvest_success",
                    "{message}",
                    "{message}"),
                Spec("POT-SPRAY-SUCCESS", NotificationCategory.Pot, NotificationSeverity.Success, NotificationChannel.Gameplay, false, false, false, 0f,
                    "notif.pot_spray_success",
                    "{message}",
                    "{message}"),
                Spec("POT-UPROOT-SUCCESS", NotificationCategory.Pot, NotificationSeverity.Success, NotificationChannel.Gameplay, false, false, false, 0f,
                    "notif.pot_uproot_success",
                    "{message}",
                    "{message}"),
                Spec("POT-ACTION-SUCCESS", NotificationCategory.Pot, NotificationSeverity.Success, NotificationChannel.Gameplay, false, false, false, 0f,
                    "notif.pot_action_success",
                    "{message}",
                    "{message}"),

                Spec("POT-WATER-FAILED", NotificationCategory.Pot, NotificationSeverity.Danger, NotificationChannel.Gameplay, false, false, false, 0f,
                    "notif.pot_water_failed",
                    "{message}",
                    "{message}"),
                Spec("POT-LIGHT-FAILED", NotificationCategory.Pot, NotificationSeverity.Danger, NotificationChannel.Gameplay, false, false, false, 0f,
                    "notif.pot_light_failed",
                    "{message}",
                    "{message}"),
                Spec("POT-PLANT-FAILED", NotificationCategory.Pot, NotificationSeverity.Danger, NotificationChannel.Gameplay, false, false, false, 0f,
                    "notif.pot_plant_failed",
                    "{message}",
                    "{message}"),
                Spec("POT-FERTILIZE-FAILED", NotificationCategory.Pot, NotificationSeverity.Danger, NotificationChannel.Gameplay, false, false, false, 0f,
                    "notif.pot_fertilize_failed",
                    "{message}",
                    "{message}"),
                Spec("POT-HARVEST-FAILED", NotificationCategory.Pot, NotificationSeverity.Danger, NotificationChannel.Gameplay, false, false, false, 0f,
                    "notif.pot_harvest_failed",
                    "{message}",
                    "{message}"),
                Spec("POT-SPRAY-FAILED", NotificationCategory.Pot, NotificationSeverity.Danger, NotificationChannel.Gameplay, false, false, false, 0f,
                    "notif.pot_spray_failed",
                    "{message}",
                    "{message}"),
                Spec("POT-UPROOT-FAILED", NotificationCategory.Pot, NotificationSeverity.Danger, NotificationChannel.Gameplay, false, false, false, 0f,
                    "notif.pot_uproot_failed",
                    "{message}",
                    "{message}"),
                Spec("POT-ACTION-FAILED", NotificationCategory.Pot, NotificationSeverity.Danger, NotificationChannel.Gameplay, false, false, false, 0f,
                    "notif.pot_action_failed",
                    "{message}",
                    "{message}"),
                Spec("PH-COUNTDOWN-001", NotificationCategory.Ph, NotificationSeverity.Warning, NotificationChannel.Gameplay, true, false, true, 2f,
                    "warn.ph_countdown",
                    "⚠️ {plant} tra {days} giorni morirà (pH estremo).",
                    "⚠️ {plant} will die in {days} days (extreme pH)."),
                Spec("PH-DEATH-001", NotificationCategory.Ph, NotificationSeverity.Danger, NotificationChannel.Gameplay, false, false, false, 0f,
                    "danger.ph_death",
                    "🚨 {plant} morta per pH estremo!",
                    "🚨 {plant} died from extreme pH!"),
                Spec("PLANT-DEATH-001", NotificationCategory.Pot, NotificationSeverity.Danger, NotificationChannel.Gameplay, false, false, false, 0f,
                    "danger.plant_death",
                    "🚨 Pianta morta! {reason}",
                    "🚨 Plant died! {reason}"),
                Spec("WATER-001", NotificationCategory.Ecosystem, NotificationSeverity.Info, NotificationChannel.Gameplay, false, false, false, 2f,
                    "notif.water_001",
                    "Raccolta acqua piovana: {amount}",
                    "Collected rainwater: {amount}"),
                Spec("SPORE-001", NotificationCategory.Inventory, NotificationSeverity.Info, NotificationChannel.Gameplay, false, false, false, 2f,
                    "notif.spore_001",
                    "Ottenute spore!",
                    "You got a spore!"),
                Spec("INV-FRUIT-001", NotificationCategory.Inventory, NotificationSeverity.Info, NotificationChannel.Gameplay, false, false, false, 2f,
                    "notif.inv_fruit_001",
                    "Nuovo frutto aggiunto all'inventario: {amount}",
                    "New fruit added to Inventory: {amount}"),
                Spec("LGT-001", NotificationCategory.System, NotificationSeverity.Info, NotificationChannel.Gameplay, false, false, false, 2f,
                    "notif.lgt_001",
                    "{message}",
                    "{message}"),
                Spec("LGT-003", NotificationCategory.System, NotificationSeverity.Info, NotificationChannel.Gameplay, false, false, false, 2f,
                    "notif.lgt_003",
                    "{message}",
                    "{message}"),
                Spec("LGT-004", NotificationCategory.System, NotificationSeverity.Info, NotificationChannel.Gameplay, false, false, false, 2f,
                    "notif.lgt_004",
                    "{message}",
                    "{message}"),

                // ===== INVENTORY =====
                Spec("INV-000", NotificationCategory.Inventory, NotificationSeverity.Info, NotificationChannel.Gameplay, false, false, false, 10f,
                    "notif.inv000",
                    "Inventario aperto",
                    "Inventory accessed"),
                Spec("ITEM-GET", NotificationCategory.Inventory, NotificationSeverity.Info, NotificationChannel.Gameplay, false, true, false, 1f,
                    "notif.item_get",
                    "Ottenuto da {location}",
                    "Obtained from {location}"),
                Spec("INV-REM", NotificationCategory.Inventory, NotificationSeverity.Info, NotificationChannel.Gameplay, false, false, false, 2f,
                    "notif.inv_rem",
                    "Rimosso dall’inventario: {item} {delta}",
                    "Removed from Inventory: {item} {delta}"),
                Spec("HYD-001", NotificationCategory.Player, NotificationSeverity.Info, NotificationChannel.Gameplay, false, false, false, 15f,
                    "notif.hyd001",
                    "Hai bevuto: Idratazione +{deltaHyd}% — +{deltaAct} Azione",
                    "You drank: Hydration +{deltaHyd}% — +{deltaAct} Action"),

                // ===== DIARY / RESEARCH / WIKI =====
                Spec("SPORAE-001", NotificationCategory.Diary, NotificationSeverity.Info, NotificationChannel.Gameplay, false, false, false, 15f,
                    "notif.sporae001",
                    "SPORAE Diary aperto",
                    "SPORAE Diary accessed"),
                Spec("RES-001", NotificationCategory.Research, NotificationSeverity.Info, NotificationChannel.Gameplay, false, false, false, 0f,
                    "notif.res001",
                    "Ricerca avviata: {nodeTitle}",
                    "Research started: {nodeTitle}"),
                Spec("WIKI-UNLOCK", NotificationCategory.Wiki, NotificationSeverity.Success, NotificationChannel.Gameplay, false, false, false, 0f,
                    "notif.wiki_unlock",
                    "{plantType} aggiunta a WIKI PLANTS",
                    "{plantType} added to WIKI PLANTS"),
                Spec("RES-UNLOCK", NotificationCategory.Research, NotificationSeverity.Success, NotificationChannel.Gameplay, false, false, false, 0f,
                    "notif.res_unlock",
                    "Specie individuale sbloccata per studio",
                    "Individual species unlocked for study"),

                // ===== REPUTATION =====
                Spec("REP-CHANGE", NotificationCategory.Reputation, NotificationSeverity.Info, NotificationChannel.Gameplay, false, false, false, 5f,
                    "notif.rep_change",
                    "Reputazione {faction} {delta}",
                    "{faction} reputation {delta}"),

                // ===== WATCHERS: DANGER PERSISTENTI / WARNINGS =====
                Spec("PH-ULTRA-ACID", NotificationCategory.Ph, NotificationSeverity.Danger, NotificationChannel.Gameplay, true, false, true, 0f,
                    "danger.ph_ultra_acid",
                    "pH ULTRA ACIDO rilevato ({ph}). Stabilizzare subito.",
                    "ULTRA ACID pH detected ({ph}). Stabilize immediately."),
                Spec("PH-ULTRA-BASIC", NotificationCategory.Ph, NotificationSeverity.Danger, NotificationChannel.Gameplay, true, false, true, 0f,
                    "danger.ph_ultra_basic",
                    "pH ULTRA BASICO rilevato ({ph}). Stabilizzare subito.",
                    "ULTRA BASIC pH detected ({ph}). Stabilize immediately."),
                Spec("PH-003", NotificationCategory.Ph, NotificationSeverity.Warning, NotificationChannel.Gameplay, true, false, true, 5f,
                    "warn.ph_unstable",
                    "pH Dome instabile ({ph})",
                    "Dome pH unstable ({ph})"),
                Spec("PH-RISK-COUNTDOWN", NotificationCategory.Ph, NotificationSeverity.Warning, NotificationChannel.Gameplay, true, false, true, 2f,
                    "warn.ph_risk_countdown",
                    "⚠️ {potId}: {plant} rischia la morte in {days} giorni (pH estremo).",
                    "⚠️ {potId}: {plant} may die in {days} days (extreme pH)."),

                Spec("WAT-OVR-WARN", NotificationCategory.Water, NotificationSeverity.Warning, NotificationChannel.Gameplay, true, false, true, 5f,
                    "warn.water_over",
                    "⚠️ Overwatering su {potId} ({pct}%). Rischio muffe.",
                    "⚠️ Overwatering on {potId} ({pct}%). Mold risk."),
                Spec("WAT-OVR-DANGER", NotificationCategory.Water, NotificationSeverity.Danger, NotificationChannel.Gameplay, true, false, true, 0f,
                    "danger.water_over",
                    "🚨 Overwatering persistente su {potId} ({days} giorni).",
                    "🚨 Persistent overwatering on {potId} ({days} days)."),

                Spec("LGT-STR-100", NotificationCategory.Light, NotificationSeverity.Danger, NotificationChannel.Gameplay, true, false, true, 0f,
                    "danger.light_stress_100",
                    "🚨 Light stress 100% su {potId}. Regola il LED.",
                    "🚨 Light stress 100% on {potId}. Adjust LED."),

                Spec("FRT-MISSING-BLOCK", NotificationCategory.Fertilizer, NotificationSeverity.Danger, NotificationChannel.Gameplay, true, false, true, 0f,
                    "danger.fertilizer_missing",
                    "🚨 {potId}: fertilizzante mancante. Crescita bloccata.",
                    "🚨 {potId}: fertilizer missing. Growth blocked."),
                Spec("FRT-OUT-RANGE", NotificationCategory.Fertilizer, NotificationSeverity.Warning, NotificationChannel.Gameplay, true, false, true, 10f,
                    "warn.fertilizer_out_range",
                    "⚠️ Fertilizzante fuori range su {potId}. Crescita rallentata.",
                    "⚠️ Fertilizer out of range on {potId}. Growth slowed."),

                Spec("MLD-RISK-CRIT", NotificationCategory.Mold, NotificationSeverity.Danger, NotificationChannel.Gameplay, true, false, true, 0f,
                    "danger.mold_crit",
                    "🚨 Rischio muffe CRITICO su {potId}.",
                    "🚨 CRITICAL mold risk on {potId}."),
                Spec("MLD-INFESTED", NotificationCategory.Mold, NotificationSeverity.Danger, NotificationChannel.Gameplay, true, false, true, 0f,
                    "danger.mold_infested",
                    "🚨 Infestazione muffe su {potId}.",
                    "🚨 Mold infestation on {potId}."),
                Spec("MLD-201", NotificationCategory.Mold, NotificationSeverity.Danger, NotificationChannel.Gameplay, true, false, true, 0f,
                    "danger.mld201",
                    "Muffa rilevata in {potId}",
                    "Mold detected in {potId}"),

                // ===== LORE TOPICS (starter) =====
                Spec("LOR-VLT-001", NotificationCategory.Lore, NotificationSeverity.Info, NotificationChannel.Lore, false, false, false, 90f,
                    "lore.vlt.001",
                    "📡 Telemetria: variazioni microclima nei condotti.",
                    "📡 Telemetry: microclimate fluctuation in ventilation ducts."),
                Spec("LOR-ECO-001", NotificationCategory.Lore, NotificationSeverity.Info, NotificationChannel.Lore, false, false, false, 90f,
                    "lore.eco.001",
                    "Le spore reagiscono al pH come se ricordassero qualcosa.",
                    "Spores react to pH as if they remember something."),
                Spec("LOR-MKT-001", NotificationCategory.Lore, NotificationSeverity.Info, NotificationChannel.Lore, false, false, false, 120f,
                    "lore.mkt.001",
                    "Sussurri: \"qualcuno paga bene per semi Pure… senza domande\".",
                    "Whispers: \"someone pays well for Pure seeds… no questions\"."),
            };

            // Per rispettare “39 tipologie”, aggiungiamo placeholder per codici ancora non implementati a call-site:
            // - Questi non rompono nulla: servono solo per debug console/push manuale.
            // (Puoi estendere qui con altri topic e codici in modo data-driven).

            return list;
        }

        private static NotificationTypeSpec Spec(
            string code,
            NotificationCategory category,
            NotificationSeverity severity,
            NotificationChannel channel,
            bool dangerPersistent,
            bool isItem,
            bool isStateDriven,
            float cooldown,
            string locKey,
            string it,
            string en)
        {
            return new NotificationTypeSpec
            {
                Code = code,
                Category = category,
                DefaultSeverity = severity,
                Channel = channel,
                IsDangerPersistent = dangerPersistent,
                IsItemLayout = isItem,
                IsStateDriven = isStateDriven,
                CooldownSeconds = cooldown,
                LocKey = locKey,
                TemplateIt = it,
                TemplateEn = en
            };
        }
    }
}


