using System.Collections.Generic;
using System.Text.RegularExpressions;
using UnityEngine;

namespace Sporae.Core.Localization
{
    /// <summary>
    /// Punto centrale per la localizzazione del gioco.
    /// Predisposizione al multilanguage: usare GetString(key) per testi futuri;
    /// attualmente i testi sono ancora in gran parte hardcoded in italiano.
    /// Estendibile con tabelle da JSON/ScriptableObject.
    /// </summary>
    public static class LocalizationManager
    {
        private static readonly Regex TokenRegex = new Regex(@"\{([a-zA-Z0-9_]+)\}", RegexOptions.Compiled);

        private static readonly Dictionary<string, (string It, string En)> Table = new Dictionary<string, (string, string)>
        {
            { "menu.options", ("Opzioni", "Options") },
            { "menu.load", ("Carica", "Load") },
            { "menu.load_game", ("Carica partita", "Load Game") },
            { "menu.save", ("Salva", "Save") },
            { "menu.continue", ("Continua", "Continue") },
            { "menu.new_game", ("Nuova partita", "New Game") },
            { "menu.play_demo", ("Gioca demo", "Play Demo") },
            { "menu.credits", ("Credits", "Credits") },
            { "menu.settings", ("Impostazioni", "Settings") },
            { "menu.exit_sporium", ("Esci da Sporium", "Exit Sporium") },
            { "menu.quit", ("Esci", "Quit") },
            { "menu.loading_progress", ("Caricamento {percent}%", "Loading {percent}%") },
            { "menu.loading_ready", ("Caricamento completato ({percent}%)", "Loading complete ({percent}%)") },
            { "menu.loading_continue", ("Premi un tasto qualsiasi per iniziare", "Press any key to start") },

            { "options.language", ("Lingua", "Language") },
            { "options.language.auto", ("Sistema (Auto)", "System (Auto)") },
            { "options.language.it", ("Italiano", "Italian") },
            { "options.language.en", ("English", "English") },
            { "options.title", ("OPZIONI", "OPTIONS") },
            { "options.subtitle", ("Configura lingua e preferenze di sessione", "Configure language and session preferences") },
            { "options.language.description", ("Scegli la lingua dei testi di gioco.", "Choose the language for game text.") },
            { "options.audio.title", ("Audio", "Audio") },
            { "options.audio.description", ("Apri il pannello volume audio esistente.", "Open the existing audio volume panel.") },
            { "options.audio.open", ("AUDIO", "AUDIO") },
            { "options.sound_volume", ("Volume suoni", "Sound Volume") },
            { "options.music_volume", ("Volume musica", "Music Volume") },

            { "notifications.title", ("NOTIFICHE", "NOTIFICATIONS") },
            { "notifications.added_to_inventory", ("AGGIUNTO ALL'INVENTARIO", "ADDED TO INVENTORY") },

            { "inventory.title", ("INVENTARIO", "INVENTORY") },
            { "inventory.subtitle", ("Oggetti nel tuo inventario", "Items in your inventory") },
            { "inventory.empty", ("Nessun oggetto in inventario.", "No items in inventory.") },
            { "inventory.select", ("Seleziona", "Select") },
            { "inventory.drink", ("Bevi", "Drink") },
            { "inventory.eat", ("Mangia", "Eat") },
            { "inventory.use", ("Usa", "Use") },
            { "inventory.cancel", ("ANNULLA", "CANCEL") },
            { "inventory.decay_line", ("SI DETERIORA IN: {days} giorni. Mettilo in Seed Storage o Dispensa Refrigerata per freezarlo.", "DECAYS IN: {days} days. Move to Seed Storage or Refrigerated Pantry to freeze.") },

            { "inventory.vault_badge", ("VAULT-07 TERMINAL", "VAULT-07 TERMINAL") },
            { "inventory.database_title", ("INVENTORY DATABASE", "INVENTORY DATABASE") },
            { "inventory.close", ("[CHIUDI]", "[CLOSE]") },
            { "inventory.stats.h2o", ("H2O: {n}L", "H2O: {n}L") },
            { "inventory.stats.actions", ("AZIONI: {l}/{m}", "ACTIONS: {l}/{m}") },
            { "inventory.stats.items", ("ITEM: {n}", "ITEMS: {n}") },
            { "inventory.filter_all", ("TUTTI", "ALL") },
            { "inventory.filter_spores", ("SPORE", "SPORES") },
            { "inventory.filter_seeds", ("SEMI", "SEEDS") },
            { "inventory.filter_organic", ("ORGANICO", "ORGANIC") },
            { "inventory.filter_reagents", ("REAGENTI", "REAGENTS") },
            { "inventory.filter_plants", ("PIANTE", "PLANTS") },
            { "inventory.filter_tools", ("STRUMENTI", "TOOLS") },
            { "inventory.filter_food", ("CIBO", "FOOD") },
            { "inventory.filter_bio", ("BIO-MAT", "BIO-MAT") },
            { "inventory.footer_version", ("VAULT-07-TERMINAL-ACCESS-INV-DB-v2.3.1", "VAULT-07-TERMINAL-ACCESS-INV-DB-v2.3.1") },
            { "inventory.footer_hint", ("PREMI ESC PER USCIRE • CLIC SULL'ITEM PER I DETTAGLI", "PRESS ESC TO EXIT • CLICK ITEM FOR DETAILS") },
            { "inventory.row.view", ("VEDI", "VIEW") },
            { "inventory.row.use", ("USA", "USE") },
            { "inventory.expand_show", ("MOSTRA TUTTO ({n} in più)", "SHOW ALL ({n} more)") },
            { "inventory.expand_less", ("MOSTRA MENO", "SHOW LESS") },
            { "inventory.confirm_action", ("CONFERMA AZIONE", "CONFIRM ACTION") },
            { "inventory.confirm_use", ("Usare questo item? {name}", "Use this item? {name}") },
            { "inventory.confirm_yes", ("SÌ", "YES") },
            { "inventory.confirm_no", ("NO", "NO") },
            { "inventory.detail.code", ("CODICE", "CODE") },
            { "inventory.detail.qty", ("QTA", "QTY") },
            { "inventory.detail.use_item", ("USA ITEM", "USE ITEM") },
            { "inventory.detail.inspect", ("Vedi Dettaglio", "View details") },
            { "inventory.detail_select_prompt", ("Seleziona un oggetto dalla lista (VEDI / USA) per i dettagli.", "Select an item from the list (VIEW / USE) for details.") },
            { "inventory.detail.category", ("CATEGORIA", "CATEGORY") },
            { "inventory.detail.genetics", ("GENETICA", "GENETICS") },
            { "inventory.detail.origin", ("ORIGINE", "ORIGIN") },
            { "inventory.detail.lab", ("PIPELINE LAB", "LAB PIPELINE") },
            { "inventory.detail.powers", ("POTERI", "POWERS") },
            { "inventory.detail.economy", ("ECONOMIA", "ECONOMY") },
            { "inventory.detail.na", ("—", "—") },
            { "inventory.detail.sell", ("VENDITA", "SELL") },
            { "inventory.detail.buy", ("ACQUISTO", "BUY") },
            { "inventory.detail.quality", ("QUALITÀ", "QUALITY") },
            { "inventory.detail.stability", ("STABILITÀ", "STABILITY") },
            { "inventory.detail.condition_label", ("Condizione", "Condition") },
            { "inventory.detail.use_effect_label", ("EFFETTO ALL'USO", "ON USE") },
            { "inventory.detail.provenance", ("PROVENIENZA", "PROVENANCE") },
            { "inventory.detail.family_alignment", ("FAMIGLIA / FAZIONE", "FAMILY / FACTION") },
            { "inventory.detail.use_effect_water_potable", ("All'uso: idratazione operatore (acqua potabile).", "On use: operator hydration (potable water).") },
            { "inventory.detail.use_effect_water_raw", ("All'uso: non bevibile; impieghi tipo irrigazione / processi che richiedono acqua grezza.", "On use: not drinkable; irrigation / processes that need raw water.") },
            { "inventory.detail.use_effect_food", ("All'uso: recupero idratazione tramite apporto alimentare sintetico.", "On use: hydration recovery via synthetic food intake.") },
            { "inventory.detail.use_effect_fruit_pure", ("All'uso: recupero idratazione (frutto puro / alto valore nutrizionale).", "On use: hydration recovery (pure / high-nutrition fruit).") },
            { "inventory.detail.use_effect_fruit_standard", ("All'uso: recupero idratazione (frutto standard).", "On use: hydration recovery (standard fruit).") },
            { "inventory.detail.use_effect_context", ("All'uso: dipende dal contesto (Dome, laboratorio, missioni).", "On use: depends on context (Dome, lab, missions).") },
            { "inventory.use_disabled_tt", ("Azione non disponibile per questo item.", "This action is not available for this item.") },
            { "inventory.inspect_disabled_tt", ("Ispezione avanzata non ancora collegata per questo item.", "Detailed inspection is not linked for this item yet.") },
            { "inventory.item_summary_default", ("Risorsa per sistemi e routine del vault.", "Resource for vault systems and routines.") },
            { "inventory.item_summary_water_raw", ("Irrigazione e processi che richiedono acqua grezza.", "Irrigation and processes that use raw water.") },
            { "inventory.item_summary_water_potable", ("Idratazione operatore: consumo sicuro.", "Operator hydration: safe consumption.") },
            { "inventory.item_summary_synth_food", ("Recupera azioni giornaliere tramite apporto alimentare sintetico.", "Restores daily action budget via synthetic nutrition.") },
            { "inventory.item_summary_spore", ("Campione genetico per laboratorio e fusione.", "Genetic sample for lab work and fusion.") },
            { "inventory.item_summary_seed", ("Seme per piantagione in Dome o pipeline lab.", "Seed for planting in the Dome or lab pipeline.") },
            { "inventory.item_summary_fruit", ("Prodotto botanico: analisi, consumo o vendita (mercato).", "Botanical product: analysis, consumption, or market sale.") },
            { "inventory.item_summary_tool", ("Strumento o input per operazioni in Dome o routine.", "Tool or input for Dome operations and routines.") },
            { "inventory.item_summary_reagent", ("Reagente per incubatore, sintesi o processi di laboratorio.", "Reagent for incubator, synthesis, or lab processes.") },
            { "inventory.item_summary_bio", ("Materiale biologico per clonazione o compostaggio.", "Biomaterial for cloning or composting.") },
            { "inventory.item_summary_whole_plant", ("Pianta sradicata: rivedi carta pianta o usi in laboratorio.", "Uprooted plant: inspect plant data or use in the lab.") },

            { "player_status.hydration", ("IDRATAZIONE", "HYDRATION") },
            { "player_status.diary", ("Diario SPORAE", "SPORAE Diary") },
            { "player_status.low_action_warning", ("▲ -1 Azione se <40%", "▲ -1 Action if <40%") },

            { "save.title.save", ("SALVA PARTITA", "SAVE GAME") },
            { "save.title.load", ("CARICA PARTITA", "LOAD GAME") },
            { "save.title.default", ("SALVATAGGI VAULT", "VAULT SAVES") },
            { "save.subtitle.default", ("Seleziona uno slot — stile terminale VLT-01", "Select a slot — VLT-01 terminal style") },
            { "save.subtitle.save", ("Scegli uno slot — i dati esistenti verranno sovrascritti.", "Choose a slot — existing data will be overwritten.") },
            { "save.subtitle.load", ("Seleziona uno slot con salvataggio valido.", "Select a slot with a valid save.") },
            { "save.summary.filled", ("{slot} — Giorno {day}, Piante in Dome {plants}, CRY {cry} — {timestamp}", "{slot} — Day {day}, Plants in Dome {plants}, CRY {cry} — {timestamp}") },
            { "save.summary.empty_for_save", ("{slot} — Vuoto (salva qui)", "{slot} — Empty (save here)") },
            { "save.summary.empty_for_load", ("{slot} — Nessun salvataggio", "{slot} — No save data") },
            { "save.action.save", ("Salva", "Save") },
            { "save.action.load", ("Carica", "Load") },
            { "save.action.delete", ("Elimina", "Delete") },
            { "save.action.close", ("CHIUDI", "CLOSE") },

            // Plant condition display (shared HUD / terminal)
            { "plant_condition.dead", ("Morta", "Dead") },
            { "plant_condition.healthy_overwatering", ("Sana (Overwatering)", "Healthy (Overwatering)") },
            { "plant_condition.rigogliosa", ("Rigogliosa", "Lush") },
            { "plant_condition.sana", ("Sana", "Healthy") },
            { "plant_condition.appassita", ("Appassita", "Wilting") },
            { "plant_condition.critica", ("Critica", "Critical") },
            { "plant_condition.unknown", ("Sconosciuta", "Unknown") },

            // Dome Status HUD
            { "dome_hud.stat.fertilizer", ("FERTILIZZANTE", "FERTILIZER") },
            { "dome_hud.stat.led", ("LUCE LED", "LED LIGHT") },
            { "dome_hud.footer.pot_hint", ("Usa il terminale POT nella Dome per operare", "Use the POT terminal in the Dome to operate.") },
            { "dome_hud.pot.empty", ("VASO VUOTO", "EMPTY POT") },
            { "dome_hud.pot.ready_plant", ("Pronto per la piantagione", "Ready for planting") },
            { "dome_hud.fertilizer.not_needed", ("NON NECESSARIO", "NOT NEEDED") },
            { "dome_hud.cryo.slot_free", ("slot disponibile", "slot available") },
            { "dome_hud.led.blue", ("BLUE", "BLUE") },
            { "dome_hud.led.red", ("RED", "RED") },
            { "dome_hud.led.off", ("OFF", "OFF") },
            { "dome_hud.stage.empty", ("Vuoto", "Empty") },
            { "dome_hud.stage.seed", ("Seme", "Seed") },
            { "dome_hud.stage.sprout", ("Germoglio", "Sprout") },
            { "dome_hud.stage.growth", ("Crescita", "Growth") },
            { "dome_hud.stage.flowering", ("Fioritura", "Flowering") },
            { "dome_hud.stage.harvest", ("Raccolta", "Harvest") },
            { "dome_hud.stage.rest", ("Riposo", "Dormant") },
            { "dome_hud.stage.n", ("Stadio {n}", "Stage {n}") },
            { "dome_hud.cond_fx.rigogliosa", ("Crescita +20% · Produzione +15%", "Growth +20% · Yield +15%") },
            { "dome_hud.cond_fx.sana", ("Crescita normale", "Normal growth") },
            { "dome_hud.cond_fx.appassita", ("Crescita -30% · Avanzamento bloccato", "Growth -30% · Progress blocked") },
            { "dome_hud.cond_fx.critica", ("Avanzamento bloccato · rischio morte", "Progress blocked · death risk") },
            { "dome_hud.cond_fx.morta", ("Nessuna crescita — esegui UPROOT", "No growth — perform UPROOT") },
            { "dome_hud.tooltip.reqs_title", ("REQUISITI E AVANZAMENTO", "REQUIREMENTS & PROGRESS") },
            { "dome_hud.tooltip.state_title", ("STATO ATTUALE", "CURRENT STATUS") },
            { "dome_hud.tooltip.condition_title", ("CONDIZIONE", "CONDITION") },
            { "dome_hud.tooltip.day_line", ("  {potId} · {stage} · Giorno {day}", "  {potId} · {stage} · Day {day}") },
            { "dome_hud.tooltip.hydration_req", ("  Idratazione   : {min}–{max}%", "  Hydration     : {min}–{max}%") },
            { "dome_hud.tooltip.led_req", ("  LED           : {led}", "  LED           : {led}") },
            { "dome_hud.tooltip.led_none", ("nessuno", "none") },
            { "dome_hud.tooltip.fert_req", ("  Fertilizzante : {min}–{max}%", "  Fertilizer    : {min}–{max}%") },
            { "dome_hud.tooltip.fert_optional_suffix", (" (opzionale Seme/Germoglio)", " (optional Seed/Sprout)") },
            { "dome_hud.tooltip.duration", ("  Durata        : {days} giorni", "  Duration      : {days} days") },
            { "dome_hud.tooltip.current_hydration", ("  Idratazione   : {pct}%", "  Hydration     : {pct}%") },
            { "dome_hud.tooltip.fert_not_stage", ("  Fertilizzante : non necessario in questo stadio", "  Fertilizer    : not required at this stage") },
            { "dome_hud.tooltip.fert_required", ("  Fertilizzante : {pct}% (necessario)", "  Fertilizer    : {pct}% (required)") },
            { "dome_hud.tooltip.fert_simple", ("  Fertilizzante : {pct}%", "  Fertilizer    : {pct}%") },
            { "dome_hud.tooltip.led_line", ("  LED           : {led}", "  LED           : {led}") },
            { "dome_hud.tooltip.light_stress", ("  Light stress  : {pct}% (20–80% ideale)", "  Light stress  : {pct}% (20–80% ideal)") },
            { "dome_hud.tooltip.optimal_days", ("  Giorni ottimali: {n}", "  Optimal days: {n}") },
            { "dome_hud.tooltip.mold_risk", ("  ⚠ Rischio muffa: livello {lvl}", "  ⚠ Mold risk: level {lvl}") },
            { "dome_hud.tooltip.mold_infested", ("  ✗ INFESTATA DA MUFFE", "  ✗ MOLD INFESTED") },
            { "dome_hud.tooltip.factors", ("  Fattori:", "  Factors:") },
            { "dome_hud.tooltip.cryo_passive", ("POTERE PASSIVO", "PASSIVE POWER") },
            { "dome_hud.tooltip.cryo_ph", ("EFFETTO pH", "pH EFFECT") },
            { "dome_hud.tooltip.drift_day", ("   Drift/giorno: {drift}", "   Drift/day: {drift}") },
            { "dome_hud.tooltip.ph_cap", ("   Cap pH: {cap}", "   pH cap: {cap}") },
            { "dome_hud.driver.hydration_low", ("Idratazione bassa ({pct}% / min {min}%)", "Low hydration ({pct}% / min {min}%)") },
            { "dome_hud.driver.overwater", ("Sovra-irrigazione ({pct}% / max {max}%)", "Overwatering ({pct}% / max {max}%)") },
            { "dome_hud.driver.fert_low", ("Fertilizzante basso ({pct}% / min {min}%)", "Low fertilizer ({pct}% / min {min}%)") },
            { "dome_hud.driver.fert_high", ("Fertilizzante in eccesso ({pct}%)", "Excess fertilizer ({pct}%)") },
            { "dome_hud.driver.light_crit", ("Light stress critico ({pct}%)", "Critical light stress ({pct}%)") },
            { "dome_hud.driver.light_high", ("Light stress elevato ({pct}%)", "High light stress ({pct}%)") },
            { "dome_hud.driver.mold_prune", ("INFESTATA DA MUFFE — esegui PRUNE", "MOLD INFESTED — perform PRUNE") },
            { "dome_hud.driver.mold_crit", ("Rischio muffa critico (liv. {lvl})", "Critical mold risk (lvl {lvl})") },
            { "dome_hud.driver.mold", ("Rischio muffa (liv. {lvl})", "Mold risk (lvl {lvl})") },
            { "dome_hud.driver.neglect", ("Vaso trascurato da {days} giorni", "Pot neglected for {days} days") },

            // TopBar HUD
            { "topbar.actions_tooltip_os",
                ("Azioni oggi: {left}/{max}.\nCap all'alba dalla colazione (max 5); senza cibo il cap cala; 3 giorni a 1 az. senza cibo → game over.\nVelocità di movimento da idratazione: circa {speed}% del normale.",
                 "Actions today: {left}/{max}.\nCap at dawn from breakfast (max 5); without food the cap drops; 3 days at 1 action with no food → game over.\nMovement speed from hydration: about {speed}% of normal.") },
            { "topbar.ph_modifier_none", ("Nessun modificatore attivo", "No active modifiers") },
            { "topbar.ph_cryo_empty", ("Nessun slot cryo attivo", "No active cryo slots") },
            { "topbar.ph_tip_plant_first", ("  Piantare piante dal Terminale POT per attivare il sistema di monitoraggio del pH.", "  Plant crops from the POT Terminal to enable pH monitoring.") },
            { "topbar.ph_tip_current_value", ("\n  Il valore \"CURRENT VALUE\" è il pH attuale della Dome; il drift indicato viene applicato al cambio giornata.", "\n  \"CURRENT VALUE\" is the Dome's current pH; the drift shown applies at day change.") },
            { "topbar.ph_total_stable", (" (Stabile)", " (Stable)") },
            { "topbar.plant_fallback", ("Pianta", "Plant") },
            { "topbar.ph_rotate.0", ("Aggiungi o bilancia le piante nei Pot (es. Pure vs Evil) per influenzare il baseline del pH.", "Add or balance plants in Pots (e.g. Pure vs Evil) to influence baseline pH.") },
            { "topbar.ph_rotate.1", ("Il pH della Dome influenza crescita e resa: monitora la banda (Acido/Neutro/Basico).", "Dome pH affects growth and yield: watch the band (Acid/Neutral/Base).") },
            { "topbar.ph_rotate.2", ("Overwatering sposta il pH verso l'acido; additivi e spray bilanciano. Usa le azioni con consapevolezza.", "Overwatering shifts pH acidic; additives and spray balance it. Use actions deliberately.") },
            { "topbar.ph_rotate.3", ("Condensazione e fertilizzanti contribuiscono al drift giornaliero.", "Condensation and fertilizers contribute to daily drift.") },
            { "topbar.ph_rotate.4", ("Ogni pianta nei Pot ha un impatto giornaliero sul pH: meno vasi = drift più prevedibile.", "Each plant in Pots has daily pH impact: fewer pots = more predictable drift.") },
            { "topbar.ph_rotate.5", ("Il forecast del giorno dopo include la deriva pH prevista da piante nei Pot; azioni e additivi si vedono nei modificatori attivi.", "The next-day forecast includes predicted pH drift from plants in Pots; actions and additives show under active modifiers.") },
            { "topbar.ph_rotate.6", ("Usa il Laboratorio e l'Extractor per spore e semi; il pH non influenza l'estrazione.", "Use the Lab and Extractor for spores and seeds; pH does not affect extraction.") },

            // TopBar — metriche (etichette visibili + tooltip statici da UXML)
            { "topbar.metric.actions", ("AZIONI", "ACTIONS") },
            { "topbar.metric.mutation", ("MUTAZIONE", "MUTATION") },
            { "topbar.metric.condensation", ("CONDENSAZIONE", "CONDENSATION") },
            { "topbar.metric.ph_drift", ("DRIFT pH", "DRIFT pH") },
            { "topbar.status.online", ("Online", "Online") },
            { "topbar.status.offline", ("Offline", "Offline") },
            { "topbar.ph_display_band.acid", ("Acido", "Acid") },
            { "topbar.ph_display_band.neutral", ("Neutrale", "Neutral") },
            { "topbar.ph_display_band.base", ("Basico", "Base") },
            { "topbar.ph_passive_cap_suffix", (" (cap {cap})", " (cap {cap})") },
            { "topbar.ph_passive_per_day", ("/g", "/d") },
            { "topbar.ph_tooltip.title_drift", ("STATO DRIFT pH DOME", "DOME pH DRIFT STATUS") },
            { "topbar.ph_tooltip.label_current", ("VALORE ATTUALE", "CURRENT VALUE") },
            { "topbar.ph_tooltip.oscillate_caption", ("Il Valore Oscilla come la tua coscienza", "The value drifts like your conscience") },
            { "topbar.ph_tooltip.label_modifiers", ("MODIFICATORI ATTIVI", "ACTIVE MODIFIERS") },
            { "topbar.ph_tooltip.label_total_drift", ("→ Drift giornaliero totale:", "→ Total daily drift:") },
            { "topbar.ph_tooltip.label_passive", ("SLOT PASSIVI CRYO", "CRYO PASSIVE SLOTS") },
            { "topbar.ph_tooltip.label_effects", ("EFFETTI GLOBALI", "GLOBAL EFFECTS") },
            { "topbar.ph_tooltip.label_tip", ("SUGGERIMENTO", "TIP") },

            { "topbar.actions_tt.title", ("AZIONI DISPONIBILI — CAP GIORNALIERO", "AVAILABLE ACTIONS — DAILY CAP") },
            { "topbar.actions_tt.section_current", ("STATO ATTUALE", "CURRENT STATUS") },
            { "topbar.actions_tt.current_line", ("<b>{left}</b>/<b>{max}</b> azioni rimanenti oggi", "<b>{left}</b>/<b>{max}</b> actions remaining today") },
            { "topbar.actions_tt.breakdown_header", ("BREAKDOWN CAP GIORNALIERO", "DAILY CAP BREAKDOWN") },
            { "topbar.actions_tt.total_cap", ("→ Cap giornaliero totale:", "→ Total daily cap:") },
            { "topbar.actions_tt.total_line", ("<b>{max}</b> azioni ({left} rimanenti)", "<b>{max}</b> actions ({left} remaining)") },
            { "topbar.actions_tt.hydration_header", ("IDRATAZIONE PLAYER", "PLAYER HYDRATION") },
            { "topbar.actions_tt.notes_header", ("NOTE", "NOTES") },
            { "topbar.actions_tt.breakfast_base", ("Colazione (base)", "Breakfast (base)") },
            { "topbar.actions_tt.runtime_adjust_pos", ("Regolazione runtime", "Runtime adjustment") },
            { "topbar.actions_tt.runtime_adjust_neg", ("Limite runtime", "Runtime cap") },
            { "topbar.actions_tt.tip_body", ("Devi mangiare (cibo o frutta) almeno una volta ogni due giorni: dal terzo giorno senza pasto il cap scende di 1 al giorno (minimo 1/5). Tre giorni di fila a 1 azione senza cibo → game over per fame. In futuro: moduli, bonus ambiente e item sul cap.", "Eat (food or fruit) at least once every two days: from the third day without a meal the cap drops by 1 per day (minimum 1/5). Three days in a row at 1 action with no food → game over from hunger. Future: modules, environment bonuses, and items affecting the cap.") },
            { "topbar.actions_tt.hydr_note_none", ("L’idratazione non influenza le Azioni: regola solo la velocità di movimento.", "Hydration does not affect Actions: it only affects movement speed.") },
            { "topbar.actions_tt.hydr_note_full", ("L’idratazione non influenza le Azioni: regola solo la velocità. Il cap azioni dipende dalla colazione e dalla fame (mangiare almeno ogni 2 giorni).", "Hydration does not affect Actions: it only affects speed. The action cap depends on breakfast and hunger (eat at least every 2 days).") },
            { "topbar.actions_tt.move_speed_empty", ("Velocità di movimento: —", "Movement speed: —") },
            { "topbar.actions_tt.move_speed_ok", ("Velocità di movimento: <b>100%</b> (H {h}% — nessuna penalità)", "Movement speed: <b>100%</b> (H {h}% — no penalty)") },
            { "topbar.actions_tt.move_speed_mid", ("Velocità di movimento: <b>~{mul}%</b> del normale (H {h}% — leggera penalità sotto il 50%)", "Movement speed: <b>~{mul}%</b> of normal (H {h}% — light penalty below 50%)") },
            { "topbar.actions_tt.move_speed_low", ("Velocità di movimento: <b>~{mul}%</b> del normale (H {h}% — forte penalità sotto il 25%)", "Movement speed: <b>~{mul}%</b> of normal (H {h}% — heavy penalty below 25%)") },
            { "topbar.actions_tt.move_speed_crit", ("Velocità di movimento: <b>minima</b> (H ≈ 0% — rischio game over se resti a 0% per 2 giorni)", "Movement speed: <b>minimal</b> (H ≈ 0% — game over risk if you stay at 0% for 2 days)") },

            { "topbar.condensation.title", ("CONDENSAZIONE", "CONDENSATION") },
            { "topbar.condensation.level_caption", ("LIVELLO ATTUALE", "CURRENT LEVEL") },
            { "topbar.condensation.tip_caption", ("SUGGERIMENTO", "TIP") },
            { "topbar.condensation.tip_body", ("💡 <color=#7FFF7A>L'intervallo ottimale è 70-85%. Monitora ogni giorno per evitare problemi.</color>", "💡 <color=#7FFF7A>The optimal range is 70–85%. Check daily to avoid issues.</color>") },
            { "topbar.condensation.collect", ("Raccogli", "Collect") },
            { "topbar.condensation.body_1", ("La <color=#5DB6E3>condensazione</color> è acqua grezza (WAT-RAW) raccolta dalla traspirazione delle piante (0-100%).", "<color=#5DB6E3>Condensation</color> is raw water (WAT-RAW) collected from plant transpiration (0–100%).") },
            { "topbar.condensation.body_2_high", ("Oltre il 50%, l'umidità ambientale aggiunge <color=#FF0000>giorni virtuali</color> al <color=#FF0000>Rischio Muffa</color> di tutte le piante (fino a +1,5g/giorno).", "Above 50%, ambient humidity adds <color=#FF0000>virtual days</color> to all plants' <color=#FF0000>Mold Risk</color> (up to +1.5d/day).") },
            { "topbar.condensation.body_2_high_extra", ("<color=#FF0000>Attualmente aggiunge +{v} giorni virtuali/giorno</color>", "<color=#FF0000>Currently adds +{v} virtual days/day</color>") },
            { "topbar.condensation.body_2_low", ("Oltre il 50%, l'umidità ambientale aggiunge <color=#FF0000>giorni virtuali</color> al <color=#FF0000>Rischio Muffa</color> di tutte le piante (fino a +1,5g/giorno).", "Above 50%, ambient humidity adds <color=#FF0000>virtual days</color> to all plants' <color=#FF0000>Mold Risk</color> (up to +1.5d/day).") },
            { "topbar.condensation.body_3", ("Raccogliere azzera la %, rimuove i giorni virtuali e produce acqua grezza: <color=#FFA500>più aspetti, maggiore è la ricompensa ma anche il rischio muffa</color>.", "Collecting resets %, removes virtual days, and yields raw water: <color=#FFA500>the longer you wait, the higher the reward — and mold risk</color>.") },
            { "topbar.condensation.body_reward", ("<b>Ricompensa stimata:</b> {min}-{max} WAT-RAW", "<b>Estimated reward:</b> {min}–{max} WAT-RAW") },
            { "topbar.condensation.body_prod_today", ("<b>Produzione di oggi:</b> {v}%", "<b>Today's production:</b> {v}%") },
            { "topbar.condensation.body_prod_tomorrow", ("<b>Stima di domani:</b> ~{v}%", "<b>Tomorrow estimate:</b> ~{v}%") },
            { "topbar.condensation.body_led_bonus", ("✨ <color=#00FF00>Bonus LED attivo: +2 WAT-RAW</color>", "✨ <color=#00FF00>Active LED bonus: +2 WAT-RAW</color>") },

            { "topbar.mutation_tt.title", ("INDICE DI MUTAZIONE", "MUTATION INDEX") },
            { "topbar.mutation_tt.para_stable", ("IM basso: predomina la stabilità e le linee Pure restano più prevedibili. Meno mutazioni spontanee.", "Low MI: stability dominates and Pure lines stay more predictable. Fewer spontaneous mutations.") },
            { "topbar.mutation_tt.para_balanced", ("IM medio: equilibrio biologico tra ordine e variabilità. Possibili cambiamenti graduali.", "Medium MI: biological balance between order and variability. Gradual changes possible.") },
            { "topbar.mutation_tt.para_high", ("IM alto: cresce la probabilità di mutazioni spontanee e tratti inediti. Maggiore imprevedibilità — e opportunità.", "High MI: higher chance of spontaneous mutations and novel traits. More unpredictability — and opportunity.") },
            { "topbar.mutation_tt.mechanics_header", ("Meccaniche", "Mechanics") },
            { "topbar.mutation_tt.decreases", ("▼ Diminuisce con: pH stabile, assenza di spore instabili, idratazione equilibrata.", "▼ Decreases with: stable pH, no unstable spores, balanced hydration.") },
            { "topbar.mutation_tt.increases", ("▲ Aumenta con: stress ambientale, muffa, esperimenti genetici, specie Evil attive (es. Glasscap in vaso).", "▲ Increases with: environmental stress, mold, genetic experiments, active Evil species (e.g. Glasscap in pot).") },
            { "topbar.mutation_tt.breakdown_header", ("Riepilogo numerico", "Numeric summary") },
            { "topbar.mutation_tt.breakdown_base", ("Base designer: {pct}%", "Designer base: {pct}%") },
            { "topbar.mutation_tt.breakdown_glass_pos", ("Bonus Glasscap (vasi attivi): +{pct}%", "Glasscap bonus (active pots): +{pct}%") },
            { "topbar.mutation_tt.breakdown_glass_zero", ("Bonus Glasscap (vasi attivi): +0% (nessuna Glasscap in crescita)", "Glasscap bonus (active pots): +0% (no growing Glasscap)") },
            { "topbar.mutation_tt.footer", ("Non sempre un rischio — a volte è evoluzione. Monitora IM e il profilo delle piante.", "Not always a risk — sometimes it's evolution. Watch MI and plant profiles.") },
            { "topbar.mutation_band.stable", ("Stabile", "Stable") },
            { "topbar.mutation_band.balanced", ("Bilanciato", "Balanced") },
            { "topbar.mutation_band.elevated", ("Elevato", "Elevated") },

            // Compact bottom bar — tooltip CRY + pulsanti sistema
            { "cbb.cry.title", ("CRY — VALUTA DEL VAULT", "CRY — VAULT CURRENCY") },
            { "cbb.cry.balance_caption", ("SALDO ATTUALE", "CURRENT BALANCE") },
            { "cbb.cry.cycle_header", ("RIEPILOGO CICLO", "CYCLE SUMMARY") },
            { "cbb.cry.earned_today", ("Guadagnato oggi", "Earned today") },
            { "cbb.cry.spent_today", ("Speso oggi", "Spent today") },
            { "cbb.cry.net_today", ("Netto oggi", "Net today") },
            { "cbb.cry.detail_header", ("DETTAGLIO P/L", "P/L DETAIL") },
            { "cbb.cry.maint_row", ("Manutenzione Dome — P/L", "Dome maintenance — P/L") },
            { "cbb.cry.sales_row", ("Vendite piante — P/L", "Plant sales — P/L") },
            { "cbb.cry.reagents_row", ("Acquisti reagenti — P/L", "Reagent purchases — P/L") },
            { "cbb.cry.forecast_header", ("PREVISIONE DOMANI", "TOMORROW FORECAST") },
            { "cbb.cry.forecast_income", ("Entrate stimate — P/L", "Estimated income — P/L") },
            { "cbb.cry.tip_header", ("SUGGERIMENTO", "TIP") },
            { "cbb.cry.tip_body", ("Monitora il netto giornaliero per bilanciare costi e ricavi CRY.", "Watch daily net to balance CRY costs and income.") },
            { "cbb.btn.options", ("Opzioni", "Options") },
            { "cbb.btn.save", ("Salva partita", "Save game") },
            { "cbb.btn.exit", ("Esci", "Quit") },

            { "gameplay.interact.press_e", ("Premi 'E' per interagire", "Press 'E' to interact") },
            { "gameplay.interact.press_e_with", ("Premi 'E' per interagire con \"{name}\"", "Press 'E' to interact with \"{name}\"") },

            // Active missions HUD (Mission Recap)
            { "missions.panel.active", ("MISSIONI", "MISSIONS") },
            { "missions.panel.completed", ("MISSIONI COMPLETATE", "COMPLETED MISSIONS") },
            { "missions.filter.active", ("ATTIVE", "ACTIVE") },
            { "missions.filter.completed", ("COMPLETATE", "COMPLETED") },
            { "missions.empty.none", ("Nessuna missione attiva.", "No active missions.") },
            { "missions.empty.completed", ("Nessuna missione completata.", "No completed missions.") },
            { "missions.card.done", ("FATTA", "DONE") },
            { "missions.card.days", ("{n}g", "{n}d") },
            { "missions.fallback_title", ("Missione senza titolo", "Untitled mission") },
            { "missions.tooltip.no_objective", ("Nessun obiettivo", "No objective") },
            { "missions.tooltip.no_description", ("Nessuna descrizione dettagliata.", "No detailed description.") },
            { "missions.tooltip.no_reward", ("Nessuna ricompensa", "No reward") },
            { "missions.tooltip.reward_cry", ("+{n} CRY", "+{n} CRY") },
            { "missions.tooltip.deadline", ("SCADE TRA {n} GIORNI", "EXPIRES IN {n} DAYS") },
            { "missions.tooltip.objective_section", ("OBIETTIVO", "OBJECTIVE") },
            { "missions.tooltip.reward_section", ("RICOMPENSA", "REWARD") },
            { "missions.tooltip.task_prefix", ("→ ", "→ ") },
            { "missions.faction.routine", ("Routine", "Routine") },
            { "missions.faction.mercanti", ("Mercanti", "Merchants") },
            { "missions.faction.cult", ("Culto", "Cult") },
            { "missions.faction.custodi", ("Custodi", "Keepers") },
            { "missions.toast.new", ("Nuova missione: {title}", "New mission: {title}") },
            { "missions.toast.done", ("Missione completata: {title}", "Mission completed: {title}") },
            { "missions.vo.complete", ("Ottimo lavoro. Missione completata: {title}.", "Good work. Mission completed: {title}.") },

            // Food Room (kitchen)
            { "food_room.picker_stem_title", ("Seleziona cellula staminale", "Select stem cell") },
            { "food_room.stem_selected", ("CELLULA STAMINALE SELEZIONATA", "STEM CELL SELECTED") },
            { "food_room.stem_insert", ("INSERISCI CELLULA STAMINALE", "INSERT STEM CELL") },
            { "food_room.tank.ready", ("PRONTO PER LA RACCOLTA", "READY TO HARVEST") },
            { "food_room.tank.growing", ("COLTIVAZIONE IN CORSO", "CULTIVATION IN PROGRESS") },
            { "food_room.tank.msg_ready", ("Raccogli la biomassa dal pannello.", "Collect biomass from the panel.") },
            { "food_room.tank.msg_growing", ("Proliferazione cellulare in corso…", "Cell proliferation in progress…") },
            { "food_room.timer_growth", ("TIMER CRESCITA: {elapsed} / {total} giorni", "GROWTH TIMER: {elapsed} / {total} days") },
            { "food_room.energy_growing", ("COSTO ENERGIA: +{cry} CRY/giorno", "ENERGY COST: +{cry} CRY/day") },
            { "food_room.energy_zero", ("COSTO ENERGIA: 0 CRY", "ENERGY COST: 0 CRY") },
            { "food_room.quality_common", ("QUALITÀ BIOMASSA: comune", "BIOMASS QUALITY: common") },
            { "food_room.tank.inactive", ("SERBATOI DI CRESCITA INATTIVI", "GROWTH TANKS INACTIVE") },
            { "food_room.tank.msg_idle", ("Seleziona un protocollo di sintesi per avviare il ciclo di crescita.", "Select a synthesis protocol to start the growth cycle.") },
            { "food_room.timer_inactive", ("TIMER CRESCITA: inattivo", "GROWTH TIMER: inactive") },
            { "food_room.quality_na", ("QUALITÀ BIOMASSA: N/D", "BIOMASS QUALITY: N/A") },
            { "food_room.btn_collect", ("💧 RACCOGLI", "💧 COLLECT") },
            { "food_room.btn_purify", ("💧 POTABILIZZA ACQUA", "💧 PURIFY WATER") },
            { "food_room.hint_chamber", ("Seleziona una camera di crescita per avviare la coltivazione", "Select a growth chamber to start cultivation") },
            { "food_room.bar_food_ready", ("Pronto per la raccolta", "Ready to harvest") },
            { "food_room.bar_food_growing", ("Coltivazione in corso", "Cultivation in progress") },
            { "food_room.bar_water_ready", ("Pronto per la raccolta", "Ready to collect") },
            { "food_room.bar_water_progress", ("Potabilizzazione in corso", "Purification in progress") },
            { "food_room.tooltip_process_busy", ("Un processo è già attivo", "A process is already running") },
            { "food_room.chrome.header_status", ("ENV-010 • SUPPORTO VITALE ATTIVO", "ENV-010 • LIFE SUPPORT ACTIVE") },
            { "food_room.chrome.title", ("SINTESI ALIMENTARE BIOLOGICA", "BIOLOGICAL FOOD SYNTHESIS") },
            { "food_room.chrome.subtitle", ("Coltivazione di biomassa nei serbatoi • Non cotto, ma coltivato • La sopravvivenza sa di scienza. I confini etici si vendono a parte.", "Biomass cultivation in tanks • Not cooked, but grown • Survival tastes like science. Ethical boundaries sold separately.") },
            { "food_room.chrome.section_growth", ("CAMERE DI CRESCITA", "GROWTH CHAMBERS") },
            { "food_room.chrome.veg_name", ("SINTESI VEGETALE", "VEGETABLE SYNTHESIS") },
            { "food_room.chrome.veg_details", ("1 giorno · 3 unità · +1 azione", "1 day · 3 units · +1 action") },
            { "food_room.chrome.veg_desc", ("Tecnicamente commestibile, presumibilmente sicuro.", "Technically edible, presumably safe.") },
            { "food_room.chrome.fung_name", ("SINTESI FUNGINA", "FUNGAL SYNTHESIS") },
            { "food_room.chrome.fung_details", ("2 giorni · 2 unità · +2 azioni", "2 days · 2 units · +2 actions") },
            { "food_room.chrome.fung_desc", ("Cresciuto al buio. Come la tua coscienza.", "Grown in the dark. Like your conscience.") },
            { "food_room.chrome.meat_name", ("SINTESI DI CARNE", "MEAT SYNTHESIS") },
            { "food_room.chrome.meat_details", ("3 giorni · 1 unità · +3 azioni · 3× RES-PROT-001", "3 days · 1 unit · +3 actions · 3× RES-PROT-001") },
            { "food_room.chrome.meat_desc", ("Non ha mai conosciuto una madre. Non la conoscerà mai.", "Never knew a mother. Never will.") },
            { "food_room.chrome.progress_label", ("COLTIVAZIONE", "CULTIVATION") },
            { "food_room.chrome.section_hydration", ("LINEA IDRATAZIONE", "HYDRATION LINE") },
            { "food_room.chrome.hydration_label", ("GREZZA → ACQUA POTABILE", "RAW → POTABLE WATER") },
            { "food_room.chrome.hydration_flavor", ("Ogni goccia riciclata, nessuna ricordata.", "Every drop recycled, none remembered.") },
            { "food_room.chrome.units_label", ("Unità", "Units") },
            { "food_room.chrome.residual_title", ("PROTEINA RESIDUA", "RESIDUAL PROTEIN") },
            { "food_room.chrome.residual_hint", ("Per il Lab di clonazione. Eticamente ambigua, scientificamente inevitabile.", "For the cloning lab. Ethically ambiguous, scientifically inevitable.") },
            { "food_room.chrome.comment", ("Avviso: la variabilità del sapore supera la tolleranza etica. Valore nutrizionale verificato. Gusto non garantito. Consumo a discrezione dell'operatore.", "Notice: flavor variability exceeds ethical tolerance. Nutritional value verified. Taste not guaranteed. Consumption at operator discretion.") },
            { "food_room.chrome.section_life_support", ("INDICATORI SUPPORTO VITALE", "LIFE SUPPORT INDICATORS") },
            { "food_room.chrome.ls_electric", ("LIVELLO ELETTRICO", "ELECTRICAL LEVEL") },
            { "food_room.chrome.ls_core_temp", ("TEMP. NUCLEO CULINARIO", "CULINARY CORE TEMP.") },
            { "food_room.chrome.ls_reservoir", ("SERBATOIO DIGESTIVO", "DIGESTIVE RESERVOIR") },
            { "food_room.chrome.ls_nutrient", ("FLUSSO NUTRIENTI", "NUTRIENT FLOW") },
            { "food_room.chrome.ls_maint_label", ("ULTIMA MANUTENZIONE", "LAST MAINTENANCE") },
            { "food_room.chrome.ls_maint_value", ("174 giorni fa — filtri in ritardo", "174 days ago — filters overdue") },
            { "food_room.chrome.btn_start", ("▶ PROCESSO ALIMENTARE", "▶ FOOD PROCESS") },
            { "food_room.chrome.btn_harvest", ("✓ RACCOLTA", "✓ HARVEST") },
            { "food_room.synth.status_on", ("SINTETIZZATORE ATTIVO", "SYNTHESIZER ONLINE") },
            { "food_room.synth.status_off", ("SINTETIZZATORE SPENTO", "SYNTHESIZER OFFLINE") },
            { "food_room.synth.cost_on", ("MANTENIMENTO: {cry} CRY/giorno", "UPKEEP: {cry} CRY/day") },
            { "food_room.synth.cost_off", ("MANTENIMENTO: 0 CRY (OFF)", "UPKEEP: 0 CRY (OFF)") },
            { "food_room.synth.btn_on", ("ACCENDI", "TURN ON") },
            { "food_room.synth.btn_off", ("SPEGNI", "TURN OFF") },
            { "food_room.tooltip_synth_off", ("Sintetizzatore spento", "Synthesizer is offline") },
            { "food_room.hint_synth_off", ("Accendi il sintetizzatore per avviare nuove colture", "Turn on the synthesizer to start new cultures") },
            { "condense_tank.chrome.status", ("KTCH-COND-001 • SERBATOIO ONLINE", "KTCH-COND-001 • TANK ONLINE") },
            { "condense_tank.chrome.title", ("SERBATOIO DI CONDENSA", "CONDENSATE TANK") },
            { "condense_tank.chrome.subtitle", ("Raccolta e potabilizzazione acqua grezza • Linea separata dalla sintesi alimentare.", "Raw water collection and purification • Separate from food synthesis.") },
            { "condense_tank.status.ready", ("Acqua potabile pronta: {count} unità.", "Potable water ready: {count} unit(s).") },
            { "condense_tank.status.progress", ("Potabilizzazione attiva su {count} unità.", "Purification active for {count} unit(s).") },
            { "condense_tank.status.available", ("Acqua grezza disponibile: {count} unità.", "Raw water available: {count} unit(s).") },
            { "condense_tank.status.empty", ("Nessuna acqua grezza disponibile.", "No raw water available.") },
            { "condense_tank.hint_select", ("Seleziona unità di acqua grezza da potabilizzare", "Select raw water units to purify") },
            { "condense_tank.hint_collect", ("Attendi il completamento o raccogli l'acqua pronta", "Wait for completion or collect ready water") },
            { "condense_tank.condensation.title", ("RACCOLTA CONDENSA DOME", "DOME CONDENSATE COLLECTION") },
            { "condense_tank.condensation.label", ("ACCUMULO CONDENSA", "CONDENSATE ACCUMULATION") },
            { "condense_tank.condensation.flavor", ("Condensa generata dalla Dome, pronta per diventare acqua grezza.", "Condensate generated by the Dome, ready to become raw water.") },
            { "condense_tank.condensation.collect", ("RACCOGLI ACQUA SPORCA", "COLLECT DIRTY WATER") },
            { "condense_tank.condensation.status_ready", ("Condensa disponibile: raccogli acqua sporca.", "Condensate available: collect dirty water.") },
            { "condense_tank.condensation.status_empty", ("Accumulo insufficiente.", "Insufficient accumulation.") },

            // Refrigerated pantry (Dispensa HUD)
            { "dispensa.status.online", ("REFRIGERAZIONE ATTIVA", "REFRIGERATION ONLINE") },
            { "dispensa.status.offline", ("REFRIGERAZIONE SPENTA", "REFRIGERATION OFFLINE") },
            { "dispensa.btn.turn_on", ("ACCENDI", "TURN ON") },
            { "dispensa.btn.turn_off", ("SPEGNI", "TURN OFF") },
            { "dispensa.preservation.optimal", ("CONSERVAZIONE OTTIMALE", "PRESERVATION OPTIMAL") },
            { "dispensa.preservation.offline", ("CONSERVAZIONE OFFLINE", "PRESERVATION OFFLINE") },
            { "dispensa.maintenance", ("MANTENIMENTO: {cry} CRY/giorno", "UPKEEP: {cry} CRY/day") },
            { "dispensa.inv.qty", ("QTA: {n}", "QTY: {n}") },
            { "dispensa.chamber.stored", ("IMM. × {n}", "STORED × {n}") },
            { "dispensa.chamber.empty", ("CELLA VUOTA", "EMPTY CHAMBER") },
            { "dispensa.food.vegetable", ("Sintesi vegetale", "Vegetal Synthesis") },
            { "dispensa.food.fungus", ("Sintesi fungina", "Fungal Synthesis") },
            { "dispensa.food.meat", ("Sintesi carnosa", "Meat Synthesis") },
            { "dispensa.food.generic", ("Alimento", "Food Item") },
            { "dispensa.footer.system_online", ("› Refrigerazione attiva", "› Refrigeration system online") },
            { "dispensa.footer.system_offline", ("› Refrigerazione offline", "› Refrigeration system offline") },
            { "dispensa.log.chambers_ready", ("Celle di stoccaggio pronte", "Storage chambers ready") },
            { "dispensa.log.panel_linked", ("Pannello collegato a FoodRoomSystem", "Panel linked to FoodRoomSystem") },
            { "dispensa.log.ref_online", ("Sistema di refrigerazione attivo", "Refrigeration system online") },
            { "dispensa.log.ref_offline", ("Sistema di refrigerazione spento", "Refrigeration system offline") },
            { "dispensa.log.removed", ("Rimosso 1 {name}", "Removed 1 {name}") },
            { "dispensa.log.stored", ("Immagazzinato 1 {name}", "Stored 1 {name}") },
            { "dispensa.log.insert_blocked", ("Inserimento bloccato: refrigerazione offline", "Insert blocked: refrigeration offline") },
            { "dispensa.log.ap_blocked", ("Azioni insufficienti per movimentare la dispensa", "Not enough actions to move pantry items") },
            { "dispensa.chrome.title", ("DISPENSA REFRIGERATA", "REFRIGERATED PANTRY") },
            { "dispensa.chrome.subtitle", ("▸ 3 CELLE DI STOCCAGGIO · CONSERVAZIONE CRYO · TERMINALE CONSUMI", "▸ 3 STORAGE CHAMBERS · CRYO PRESERVATION · FOOD CONSUMPTION TERMINAL") },
            { "dispensa.chrome.section_chambers", ("CELLE DI STOCCAGGIO (3)", "STORAGE CHAMBERS (3)") },
            { "dispensa.chrome.section_inv", ("CIBO INVENTARIO", "INVENTORY FOOD") },
            { "dispensa.chrome.chamber_fungal", ("STOCCAGGIO FUNGINO", "FUNGAL STORAGE") },
            { "dispensa.chrome.chamber_meat", ("CARNE SINTETICA", "SYNTHETIC MEAT") },
            { "dispensa.chrome.chamber_vegetal", ("STOCCAGGIO VEGETALE", "VEGETAL STORAGE") },
            { "dispensa.chrome.info_temp", ("TEMP: -5°C", "TEMP: -5°C") },
            { "dispensa.chrome.info_humidity", ("UMIDITÀ: 65%", "HUMIDITY: 65%") },

            // Lab — Catalizzatore / Fusion / Extractor / Incubator (stringhe UI principali)
            { "lab_cat.status_progress", ("Stato: {n} maturazione/i in corso (fino a 3)", "Status: {n} maturation(s) in progress (up to 3)") },
            { "lab_cat.status_ready", ("Stato: Pronto — ritira spora/e maturata/e", "Status: Ready — collect mature spore(s)") },
            { "lab_cat.status_idle", ("Stato: In attesa di input (spora Raw). Fino a 3 in parallelo.", "Status: Waiting for input (Raw spore). Up to 3 in parallel.") },
            { "lab_cat.picker_title", ("Seleziona spora Raw da inserire nel Catalizzatore", "Select Raw spore to load into the Catalyser") },
            { "lab_cat.output_mature", ("Spora maturata x{count}", "Mature spore x{count}") },
            { "lab_fusion.slot_mature", ("Spora Maturata", "Mature spore") },
            { "lab_fusion.progress", ("Fusione in corso.. {pct}%", "Fusion in progress.. {pct}%") },
            { "lab_fusion.output_preseed", ("Pre-Seed x{count}", "Pre-seed x{count}") },
            { "lab_extractor.progress_in_progress", ("Estrazione in Corso.. {pct}%", "Extraction in progress.. {pct}%") },
            { "lab_extractor.done", ("Estrazione completata", "Extraction complete") },
            { "lab_extractor.picker_title", ("Seleziona item da inserire nell'Extractor", "Select item to load into the Extractor") },
            { "lab_incubator.picker_preseed", ("Seleziona Pre-Seed per l'Incubatore", "Select Pre-seed for the Incubator") },
            { "lab_incubator.picker_reagent", ("Seleziona Reagente (X o Y) dall'inventario", "Select Reagent (X or Y) from inventory") },
            { "lab_incubator.inv_preseed", ("In inventario: Pre-Seed x{count}", "In inventory: Pre-seed x{count}") },
            { "lab_incubator.profile_base", ("Ritira l'output dall'Incubatore per aggiungere i semi all'inventario.", "Collect the Incubator output to add seeds to your inventory.") },
            { "lab_incubator.profile_hybrid_detail", ("Profilo Lab: famiglia {fam}, tratti: {traits}, reagente: {reag}.\n{base}", "Lab profile: family {fam}, traits: {traits}, reagent: {reag}.\n{base}") },

            // Lab terminal — Kitchen / seed project UI
            { "lab_terminal.machine.idle", ("Idle", "Idle") },
            { "lab_terminal.machine.extractor_progress", ("In corso ({pct}%)", "In progress ({pct}%)") },
            { "lab_terminal.machine.extractor_done", ("Completato (Spore RAW rilevate: {n})", "Complete (Raw spores detected: {n})") },
            { "lab_terminal.machine.cat_progress", ("In corso (maturazione 1 giorno)", "In progress (1-day maturation)") },
            { "lab_terminal.machine.cat_done", ("Completato (Spore mature: {n})", "Complete (Mature spores: {n})") },
            { "lab_terminal.machine.fusion_progress", ("In corso ({pct}%)", "In progress ({pct}%)") },
            { "lab_terminal.machine.fusion_done", ("Completato (Pre-seed: {n})", "Complete (Pre-seed: {n})") },
            { "lab_terminal.machine.inc_progress", ("In corso (giorno {day}/2)", "In progress (day {day}/2)") },
            { "lab_terminal.machine.inc_done", ("Completato (Semi: {n})", "Complete (Seeds: {n})") },
            { "lab_terminal.btn_collect_output", ("RITIRA OUTPUT DA {machine}", "COLLECT OUTPUT FROM {machine}") },
            { "lab_terminal.btn_open_step", ("APRI STEP CORRENTE", "OPEN CURRENT STEP") },
            { "lab_terminal.btn_analysis_running", ("ANALISI IN CORSO...", "ANALYSIS RUNNING...") },
            { "lab_terminal.btn_select_type", ("SELEZIONA TIPOLOGIA", "SELECT PROJECT TYPE") },
            { "lab_terminal.status.analysis_resources", ("Progetto attivo: analisi risorse in corso...", "Active project: scanning resources...") },
            { "lab_terminal.status.analysis_waiting", ("Progetto attivo: analisi iniziale in attesa.", "Active project: initial analysis pending.") },
            { "lab_terminal.status.collect_gate", ("Progetto attivo: ritira output pronto da {machine} prima di continuare.", "Active project: collect ready output from {machine} before continuing.") },
            { "lab_terminal.status.completed_seed", ("Progetto completato: seed pronto per il ritiro.", "Project complete: seed ready to collect.") },
            { "lab_terminal.status.active_step", ("Progetto attivo ({type}): step corrente {step}.", "Active project ({type}): current step {step}.") },
            { "lab_terminal.status.last_done", ("Ultimo progetto completato. Avvia un nuovo ciclo quando vuoi.", "Last project completed. Start a new cycle whenever you want.") },
            { "lab_terminal.status.no_project", ("Nessun progetto attivo. Usa i macchinari in modalità standalone o avvia Crea Nuovo Seme.", "No active project. Use machines standalone or start Create New Seed.") },
            { "lab_terminal.step_row.extractor", ("Frutto -> Spora: {state}", "Fruit -> Spore: {state}") },
            { "lab_terminal.step_row.catalizzatore", ("Spora -> Maturazione: {state}", "Spore -> Maturation: {state}") },
            { "lab_terminal.step_row.fusion", ("Maturazione -> Pre-seed: {state}", "Maturation -> Pre-seed: {state}") },
            { "lab_terminal.step_row.incubator", ("Pre-seed -> Incubazione: {state}", "Pre-seed -> Incubation: {state}") },
            { "lab_terminal.step_state.completed", ("Completato", "Complete") },
            { "lab_terminal.step_state.in_progress", ("In corso", "In progress") },
            { "lab_terminal.step_state.todo", ("Da fare", "To do") },
            { "lab_terminal.step_state.blocked", ("Bloccato", "Locked") },
            { "lab_terminal.step.extractor", ("Frutto -> Spora", "Fruit -> Spore") },
            { "lab_terminal.step.catalizzatore", ("Spora -> Maturazione", "Spore -> Maturation") },
            { "lab_terminal.step.fusion", ("Maturazione -> Pre-seed", "Maturation -> Pre-seed") },
            { "lab_terminal.step.incubator", ("Pre-seed -> Incubazione", "Pre-seed -> Incubation") },
            { "lab_terminal.step.completed", ("Completato", "Complete") },
            { "lab_terminal.machine.extractor", ("EXTRACTOR", "EXTRACTOR") },
            { "lab_terminal.machine.catalizzatore", ("CATALIZZATORE", "CATALYSER") },
            { "lab_terminal.machine.fusion", ("FUSION", "FUSION") },
            { "lab_terminal.machine.incubator", ("INCUBATOR", "INCUBATOR") },
            { "lab_terminal.machine.generic", ("MACCHINA", "MACHINE") },
            { "lab_terminal.direction_changed", ("<color=#AFC8D8>Hai cambiato direzione in corso:</color> da {from} a {to}. Nessuna penalita, il sistema aggiorna solo i consigli.", "<color=#AFC8D8>You changed direction mid-flow:</color> from {from} to {to}. No penalty — the system only refreshes guidance.") },
            { "lab_terminal.intent.replica", ("replicare la linea di origine con coerenza.", "replicate the source line consistently.") },
            { "lab_terminal.intent.hybrid", ("combinare due linee per tratti misti.", "combine two lines for mixed traits.") },
            { "lab_terminal.intent.new_profile", ("costruire un outcome nuovo orientato da reagenti.", "build a new outcome steered by reagents.") },
            { "lab_terminal.intent.default", ("definire un risultato operativo.", "define an operational outcome.") },
            { "lab_terminal.phase.collect", ("Output pronto da {machine}: ritira prima di continuare.", "Output ready from {machine}: collect before continuing.") },
            { "lab_terminal.phase.current", ("Fase attuale: {step}.", "Current phase: {step}.") },
            { "lab_terminal.quick_intro_active", ("<color=#97A7B2>Progetto Seme ({type}):</color> obiettivo {intent} {phase}", "<color=#97A7B2>Seed Project ({type}):</color> goal {intent} {phase}") },
            { "lab_terminal.quick_intro_idle", ("<color=#97A7B2>Progetto Seme:</color> scegli un intento (Replica / Ibrido / Nuovo Profilo). E una bussola strategica, non un vincolo: il sistema consiglia, il player decide.", "<color=#97A7B2>Seed Project:</color> pick an intent (Replica / Hybrid / New Profile). It is strategic guidance, not a hard lock: the system advises, you decide.") },
            { "lab_terminal.quick_what_analysis", ("<color=#98CFFF>Step corrente:</color> analisi iniziale in corso. Il terminale sta valutando frutti in inventario e Seed Storage.", "<color=#98CFFF>Current step:</color> initial analysis running. The terminal is scanning player inventory and Seed Storage.") },
            { "lab_terminal.quick_what_pick_type", ("<color=#98CFFF>Step corrente:</color> completa la fase Analisi e scegli una tipologia progetto per ricevere consigli contestuali.", "<color=#98CFFF>Current step:</color> finish the Analysis phase and pick a project type for contextual tips.") },
            { "lab_terminal.quick_what_idle", ("<color=#98CFFF>Step corrente:</color> nessun progetto attivo. Premi CREA NUOVO SEME per avviare il flow guidato.", "<color=#98CFFF>Current step:</color> no active project. Press CREATE NEW SEED to start the guided flow.") },
            { "lab_terminal.quick_detail.extractor", ("estrai una Spora RAW da un frutto (Extractor).", "extract a Raw spore from a fruit (Extractor).") },
            { "lab_terminal.quick_detail.catalizzatore", ("matura la Spora RAW in Spora Maturata (Catalizzatore).", "mature Raw spore into Mature spore (Catalyser).") },
            { "lab_terminal.quick_detail.fusion", ("combina due Spore Maturate per ottenere un Pre-seed (Fusion).", "combine two Mature spores to obtain a Pre-seed (Fusion).") },
            { "lab_terminal.quick_detail.incubator", ("incuba il Pre-seed per ottenere il Seme finale (Incubator).", "incubate the Pre-seed to obtain the final Seed (Incubator).") },
            { "lab_terminal.quick_detail.done", ("progetto completato. Ritira il seed e avvia un nuovo ciclo se vuoi.", "project complete. Collect the seed and start a new cycle if you want.") },
            { "lab_terminal.quick_what_active", ("<color={kw}>Step corrente:</color> {detail} <color=#A4B7C5>Intento:</color> {type}. {reminder}", "<color={kw}>Current step:</color> {detail} <color=#A4B7C5>Intent:</color> {type}. {reminder}") },
            { "lab_terminal.quick_live_standalone", ("<color=#9EC8E4>Live:</color> modalità standalone. Apri i macchinari singolarmente dal terminale.", "<color=#9EC8E4>Live:</color> standalone mode. Open machines individually from the terminal.") },
            { "lab_terminal.quick_live_analysis", ("<color=#B98DFF>Live:</color> analisi combinazioni in corso ({pct}%).", "<color=#B98DFF>Live:</color> combination analysis in progress ({pct}%).") },
            { "lab_terminal.quick_live_extractor", ("<color=#B98DFF>Live:</color> Extractor in corso ({pct}%).", "<color=#B98DFF>Live:</color> Extractor in progress ({pct}%).") },
            { "lab_terminal.quick_live_catalizzatore", ("<color=#B98DFF>Live:</color> Catalizzatore in corso (1 giorno di maturazione).", "<color=#B98DFF>Live:</color> Catalyser in progress (1-day maturation).") },
            { "lab_terminal.quick_live_fusion", ("<color=#B98DFF>Live:</color> Fusion in corso ({pct}%).", "<color=#B98DFF>Live:</color> Fusion in progress ({pct}%).") },
            { "lab_terminal.quick_live_incubator", ("<color=#B98DFF>Live:</color> Incubazione in corso (giorno {day}/2).", "<color=#B98DFF>Live:</color> Incubation in progress (day {day}/2).") },
            { "lab_terminal.quick_live_idle", ("<color=#9EC8E4>Live:</color> nessun processo attivo, pronto allo step successivo.", "<color=#9EC8E4>Live:</color> no active process, ready for the next step.") },
            { "lab_terminal.outcome_wait_analysis", ("<color=#76828C>Outcome:</color> attendi la fine dell'analisi iniziale per vedere combinazioni consigliate e vincoli reali disponibili.", "<color=#76828C>Outcome:</color> wait for initial analysis to finish to see recommended combos and real constraints.") },
            { "lab_terminal.outcome_prefix", ("<color=#7EFD80>Outcome:</color> ", "<color=#7EFD80>Outcome:</color> ") },
            { "lab_terminal.outcome_raw_line", ("<color=#7EFD80>Outcome:</color> <color=#98CFFF>Spora RAW</color> pronta al ritiro | TRATTI <color=#7EFD80>{tratti}</color> | FAMIGLIA <color=#98CFFF>{fam}</color>.", "<color=#7EFD80>Outcome:</color> <color=#98CFFF>Raw spore</color> ready to collect | TRAITS <color=#7EFD80>{tratti}</color> | FAMILY <color=#98CFFF>{fam}</color>.") },
            { "lab_terminal.outcome_raw_fallback", ("<color=#7EFD80>Outcome:</color> estrazione completata. Raccogli la Spora RAW per vedere metadata e tratti.", "<color=#7EFD80>Outcome:</color> extraction complete. Collect the Raw spore to see metadata and traits.") },
            { "lab_terminal.outcome_none", ("<color=#76828C>Outcome:</color> nessun risultato ancora. Completa il primo step per produrre la prima <color=#98CFFF>Spora RAW</color>.", "<color=#76828C>Outcome:</color> no result yet. Complete the first step to produce the first <color=#98CFFF>Raw spore</color>.") },
            { "lab_terminal.outcome_line_ready_no_meta", ("<color=#98CFFF>{stage}</color> pronto, ma metadata non disponibili finche non viene ritirato nell'inventario.", "<color=#98CFFF>{stage}</color> ready, but metadata stays hidden until collected to inventory.") },
            { "lab_terminal.outcome_line_produced", ("<color=#98CFFF>{stage}</color> prodotto: <color=#7EFD80>{name}</color> | {meta}", "<color=#98CFFF>{stage}</color> produced: <color=#7EFD80>{name}</color> | {meta}") },
            { "lab_terminal.outcome_meta", ("TRATTI <color=#7EFD80>{tratti}</color> | MUTARE <color=#B98DFF>{mut}</color> | FAMIGLIA <color=#98CFFF>{fam}</color> | ORIGINE <color=#98CFFF>{orig}</color>", "TRAITS <color=#7EFD80>{tratti}</color> | MUTATE <color=#B98DFF>{mut}</color> | FAMILY <color=#98CFFF>{fam}</color> | ORIGIN <color=#98CFFF>{orig}</color>") },
            { "lab_terminal.analysis_cta_idle", ("Premi <color=#98CFFF>CREA NUOVO SEME</color> per analizzare frutti disponibili e combinazioni possibili.", "Press <color=#98CFFF>CREATE NEW SEED</color> to scan available fruits and possible combinations.") },
            { "lab_terminal.analysis_running", ("Analisi in corso... <color=#B98DFF>{pct}%</color> | scanning inventario player + Seed Storage.", "Analysis running... <color=#B98DFF>{pct}%</color> | scanning player inventory + Seed Storage.") },
            { "lab_terminal.analysis_waiting_restart", ("Analisi in attesa. Riavvia progetto per calcolare suggerimenti.", "Analysis pending. Restart the project to compute suggestions.") },
            { "lab_terminal.analysis_done", ("Analisi completata: frutti disponibili <color=#98CFFF>{total}</color> (inventario {inv} + storage {stor}) | reagenti X/Y: <color=#98CFFF>{x}</color>/<color=#98CFFF>{y}</color>.", "Analysis complete: fruits available <color=#98CFFF>{total}</color> (inventory {inv} + storage {stor}) | reagents X/Y: <color=#98CFFF>{x}</color>/<color=#98CFFF>{y}</color>.") },
            { "lab_terminal.schema.project_none", ("Progetto: --", "Project: --") },
            { "lab_terminal.schema.items_pick", ("Item necessari: seleziona una tipologia.", "Required items: select a project type.") },
            { "lab_terminal.schema.status_pick", ("Status: in attesa selezione.", "Status: awaiting selection.") },
            { "lab_terminal.schema.items_eval", ("Item necessari: in valutazione...", "Required items: evaluating...") },
            { "lab_terminal.schema.status_running", ("Status: analisi in corso.", "Status: analysis running.") },
            { "lab_terminal.schema.project_replica", ("Progetto: REPLICA", "Project: REPLICA") },
            { "lab_terminal.schema.project_hybrid", ("Progetto: IBRIDO", "Project: HYBRID") },
            { "lab_terminal.schema.project_new", ("Progetto: NUOVO PROFILO", "Project: NEW PROFILE") },
            { "lab_terminal.schema.replica_items", ("Item necessari: 2x frutto uguale (best: {type} x{count}).", "Required items: 2x same fruit (best: {type} x{count}).") },
            { "lab_terminal.schema.replica_ok", ("<color=#7EFD80>Item presenti</color>", "<color=#7EFD80>Items present</color>") },
            { "lab_terminal.schema.replica_missing", ("<color=#76828C>Item mancanti</color> (serve ancora {need} unita dello stesso frutto).", "<color=#76828C>Missing items</color> (need {need} more of the same fruit).") },
            { "lab_terminal.schema.exec_ok", ("<color=#7EFD80>Progetto eseguibile</color>", "<color=#7EFD80>Project executable</color>") },
            { "lab_terminal.schema.exec_no", ("<color=#76828C>Progetto non eseguibile</color>", "<color=#76828C>Project not executable</color>") },
            { "lab_terminal.schema.status_pair", ("Status: {items} | {proj}.", "Status: {items} | {proj}.") },
            { "lab_terminal.schema.hybrid_items", ("Item necessari: 2x frutti diversi.", "Required items: 2x different fruits.") },
            { "lab_terminal.schema.hybrid_missing_total", ("<color=#76828C>Item mancanti</color> (frutti totali {have}/2)", "<color=#76828C>Missing items</color> (total fruits {have}/2)") },
            { "lab_terminal.schema.hybrid_missing_types", ("<color=#76828C>Item mancanti</color> (tipologie disponibili {have}/2)", "<color=#76828C>Missing items</color> (types available {have}/2)") },
            { "lab_terminal.schema.new_items", ("Item necessari: 2x frutti diversi + 1x reagente (X o Y). Reagenti ora: X={x}, Y={y}.", "Required items: 2x different fruits + 1x reagent (X or Y). Reagents now: X={x}, Y={y}.") },
            { "lab_terminal.schema.new_missing_fruit", ("mancano frutti diversi", "missing different fruits") },
            { "lab_terminal.schema.new_missing_reagent", ("manca REAG-X o REAG-Y", "missing REAG-X or REAG-Y") },
            { "lab_terminal.schema.new_ok_reason", ("ok", "ok") },
            { "lab_terminal.schema.new_missing_wrap", ("<color=#76828C>Item mancanti</color> ({reason})", "<color=#76828C>Missing items</color> ({reason})") },
            { "lab_terminal.analysis_hint_done", ("Progetto completato.", "Project complete.") },
            { "lab_terminal.analysis_hint_step", ("Suggerimento step: {text}", "Step tip: {text}") },
            { "lab_terminal.analysis_initial", ("<color=#7E90A0>Intento iniziale:</color> {type}. ", "<color=#7E90A0>Initial intent:</color> {type}. ") },
            { "lab_terminal.analysis_direction", ("{initial}<color=#9CB3C4>Direzione attuale:</color> {type}. {hint}", "{initial}<color=#9CB3C4>Current direction:</color> {type}. {hint}") },
            { "lab_terminal.fruit_summary_none", ("nessun frutto disponibile", "no fruit available") },
            { "lab_terminal.analysis_same_ok", ("Frutti uguali x2: <color=#7EFD80>PRESENTE</color> ({type} x{count}).", "Same fruit x2: <color=#7EFD80>PRESENT</color> ({type} x{count}).") },
            { "lab_terminal.analysis_same_no", ("Frutti uguali x2: <color=#76828C>ASSENTE</color> (manca almeno {need} unita sul tipo piu disponibile: {type} x{count}).", "Same fruit x2: <color=#76828C>ABSENT</color> (need at least {need} more on the most stocked type: {type} x{count}).") },
            { "lab_terminal.analysis_two_ok", ("Frutti diversi x2: <color=#7EFD80>PRESENTE</color> (tipologie rilevate: {types}; {summary}).", "Different fruits x2: <color=#7EFD80>PRESENT</color> (types detected: {types}; {summary}).") },
            { "lab_terminal.analysis_two_no_total", ("Frutti diversi x2: <color=#76828C>ASSENTE</color> (frutti totali {have}/2, ne manca {need}).", "Different fruits x2: <color=#76828C>ABSENT</color> (total fruits {have}/2, missing {need}).") },
            { "lab_terminal.analysis_two_no_types", ("Frutti diversi x2: <color=#76828C>ASSENTE</color> (manca seconda tipologia: presenti {types}; {summary}).", "Different fruits x2: <color=#76828C>ABSENT</color> (missing a second type: have {types}; {summary}).") },
            { "lab_terminal.analysis_reagent_ok", ("Reagente X/Y: <color=#7EFD80>PRESENTE</color> (X:{x}, Y:{y}).", "Reagent X/Y: <color=#7EFD80>PRESENT</color> (X:{x}, Y:{y}).") },
            { "lab_terminal.analysis_reagent_no", ("Reagente X/Y: <color=#76828C>ASSENTE</color> (manca almeno REAG-X o REAG-Y).", "Reagent X/Y: <color=#76828C>ABSENT</color> (missing at least REAG-X or REAG-Y).") },
            { "lab_terminal.advice_replica_tail", ("Consiglio: usa 2 frutti della stessa origine per massima coerenza.", "Tip: use 2 fruits of the same origin for maximum consistency.") },
            { "lab_terminal.advice_hybrid_tail", ("Consiglio: usa 2 frutti diversi per aprire tratti combinati.", "Tip: use 2 different fruits to unlock combined traits.") },
            { "lab_terminal.advice_new_tail", ("Consiglio: combina frutti diversi e usa reagente X/Y per orientare outcome.", "Tip: combine different fruits and use reagent X/Y to steer the outcome.") },
            { "lab_terminal.reminder.replica.extractor", ("Reminder Replica: seleziona frutti stessa origine.", "Replica reminder: pick fruits of the same origin.") },
            { "lab_terminal.reminder.replica.cat", ("Reminder Replica: mantieni coerenza materiale nelle spore.", "Replica reminder: keep material coherence across spores.") },
            { "lab_terminal.reminder.replica.fusion", ("Reminder Replica: combina 2 spore allineate per output stabile.", "Replica reminder: fuse 2 aligned spores for a stable output.") },
            { "lab_terminal.reminder.replica.inc", ("Reminder Replica: evita deviazioni se vuoi fedelta al genitore.", "Replica reminder: avoid drift if you want parent fidelity.") },
            { "lab_terminal.reminder.replica.done", ("Replica completata: confronta outcome con l'origine.", "Replica complete: compare the outcome with the source.") },
            { "lab_terminal.reminder.hybrid.extractor", ("Reminder Ibrido: prepara 2 origini diverse.", "Hybrid reminder: prepare 2 different origins.") },
            { "lab_terminal.reminder.hybrid.cat", ("Reminder Ibrido: matura entrambe le linee prima della fusion.", "Hybrid reminder: mature both lines before fusion.") },
            { "lab_terminal.reminder.hybrid.fusion", ("Reminder Ibrido: mixa spore differenti per tratti combinati.", "Hybrid reminder: mix different spores for combined traits.") },
            { "lab_terminal.reminder.hybrid.inc", ("Reminder Ibrido: reagente Y puo aiutare la convergenza famiglia.", "Hybrid reminder: reagent Y can help family convergence.") },
            { "lab_terminal.reminder.hybrid.done", ("Ibrido completato: verifica sinergia tratti.", "Hybrid complete: check trait synergy.") },
            { "lab_terminal.reminder.new.extractor", ("Reminder Nuovo Profilo: seleziona frutti con identita lontane.", "New Profile reminder: pick fruits with distant identities.") },
            { "lab_terminal.reminder.new.cat", ("Reminder Nuovo Profilo: conserva variabilita utile al design finale.", "New Profile reminder: keep variability useful for the final design.") },
            { "lab_terminal.reminder.new.fusion", ("Reminder Nuovo Profilo: qui nasce il nuovo outcome mentale.", "New Profile reminder: the new mental outcome starts here.") },
            { "lab_terminal.reminder.new.inc", ("Reminder Nuovo Profilo: usa reagente X/Y per orientare nome/poteri.", "New Profile reminder: use reagent X/Y to steer name/powers.") },
            { "lab_terminal.reminder.new.done", ("Nuovo Profilo completato: documenta il risultato ottenuto.", "New Profile complete: note the result you obtained.") },
            { "lab_terminal.reminder.pick_type", ("Scegli una tipologia per ricevere suggerimenti mirati.", "Pick a project type for targeted tips.") },
            { "lab_terminal.type.replica", ("Replica", "Replica") },
            { "lab_terminal.type.hybrid", ("Ibrido", "Hybrid") },
            { "lab_terminal.type.new_profile", ("Nuovo Profilo", "New Profile") },
            { "lab_terminal.type.undefined", ("Non definito", "Undefined") },
            { "lab_terminal.label.seed", ("Seed", "Seed") },
            { "lab_terminal.label.preseed", ("Pre-seed", "Pre-seed") },
            { "lab_terminal.label.mature_spore", ("Spora Maturata", "Mature spore") },
            { "lab_terminal.label.raw_spore", ("Spora RAW", "Raw spore") },
            { "lab_terminal.chrome.title", ("TERMINALE LABORATORIO", "LAB TERMINAL") },
            { "lab_terminal.chrome.subtitle", ("Hub operativo del laboratorio: usa i macchinari singolarmente o avvia il flow guidato Crea Nuovo Seme.", "Lab operations hub: use each machine standalone or start the guided Create New Seed flow.") },
            { "lab_terminal.chrome.section_machines", ("MACCHINARI", "MACHINES") },
            { "lab_terminal.chrome.machines_hint", ("Modalità standalone: apri e usa ogni macchinario singolarmente, senza avviare un progetto guidato.", "Standalone mode: open and use each machine individually without starting a guided project.") },
            { "lab_terminal.chrome.machine_extractor", ("Extractor", "Extractor") },
            { "lab_terminal.chrome.machine_catalizzatore", ("Catalizzatore", "Catalyser") },
            { "lab_terminal.chrome.machine_fusion", ("Fusion (Pipette)", "Fusion (Pipettes)") },
            { "lab_terminal.chrome.machine_incubator", ("Incubator", "Incubator") },
            { "lab_terminal.chrome.btn_open", ("Apri", "Open") },
            { "lab_terminal.chrome.project_title", ("PROGETTO SEME", "SEED PROJECT") },
            { "lab_terminal.chrome.quick_static_title", ("GUIDA STATICA", "STATIC GUIDE") },
            { "lab_terminal.chrome.quick_dynamic_title", ("STATO DINAMICO", "LIVE STATUS") },
            { "lab_terminal.chrome.quick_intro_placeholder", ("Progetto Seme: pipeline guidata Frutto -> Spora -> Maturazione -> Pre-seed -> Incubazione.", "Seed Project: guided pipeline Fruit → Spore → Maturation → Pre-seed → Incubation.") },
            { "lab_terminal.chrome.quick_what_placeholder", ("Nessun progetto attivo. Premi CREA NUOVO SEME per avviare il flow guidato.", "No active project. Press CREATE NEW SEED to start the guided flow.") },
            { "lab_terminal.chrome.quick_live_placeholder", ("Live: modalità standalone.", "Live: standalone mode.") },
            { "lab_terminal.chrome.quick_outcome_placeholder", ("Outcome: nessun risultato ancora.", "Outcome: no result yet.") },
            { "lab_terminal.chrome.btn_create", ("CREA NUOVO SEME", "CREATE NEW SEED") },
            { "lab_terminal.chrome.btn_cancel", ("TERMINA PROGETTO", "END PROJECT") },
            { "lab_terminal.chrome.placeholder_image", ("IMMAGINE PROGETTO (PLACEHOLDER)", "PROJECT IMAGE PLACEHOLDER") },
            { "lab_terminal.chrome.board_title", ("LAVAGNA DIGITALE", "DIGITAL BOARD") },
            { "lab_terminal.chrome.legend_title", ("Legenda:", "Legend:") },
            { "lab_terminal.chrome.legend_inprogress", ("● In corso", "● In progress") },
            { "lab_terminal.chrome.legend_completed", ("● Completato", "● Complete") },
            { "lab_terminal.chrome.legend_todo", ("● Da fare", "● To do") },
            { "lab_terminal.chrome.legend_blocked", ("● Bloccato", "● Locked") },
            { "lab_terminal.chrome.analysis_title", ("ANALISI PROGETTO SEME", "SEED PROJECT ANALYSIS") },
            { "lab_terminal.chrome.analysis_project_type_caption", ("Tipologia progetto (consigliata, non vincolante):", "Project type (recommended, not binding):") },
            { "lab_terminal.chrome.type_replica", ("REPLICA", "REPLICA") },
            { "lab_terminal.chrome.type_hybrid", ("IBRIDO", "HYBRID") },
            { "lab_terminal.chrome.type_new_profile", ("NUOVO PROFILO", "NEW PROFILE") },
            { "lab_terminal.chrome.analysis_sheet_title", ("SCHEDA PROGETTO", "PROJECT SHEET") },
            { "lab_terminal.chrome.analysis_project_line", ("Progetto: --", "Project: --") },
            { "lab_terminal.chrome.analysis_required_placeholder", ("Item necessari: seleziona una tipologia.", "Required items: select a project type.") },
            { "lab_terminal.chrome.analysis_exec_placeholder", ("Status: in attesa selezione.", "Status: awaiting selection.") },
            { "lab_terminal.chrome.analysis_cancel", ("ANNULLA SCELTA", "CANCEL SELECTION") },
            { "lab_terminal.chrome.analysis_status_prep", ("Analisi in preparazione...", "Preparing analysis...") },

            // Pruning dialog (UGUI)
            { "pruning.title", ("✂️ Potatura", "✂️ Pruning") },
            { "pruning.body", ("Eseguire la potatura su questa pianta?", "Prune this plant?") },
            { "pruning.toggle_available", ("Aggiungi additivo basico (consuma STR-004-Basic)", "Add basic additive (consumes STR-004-Basic)") },
            { "pruning.toggle_unavailable", ("Aggiungi additivo basico (STR-004-Basic non disponibile)", "Add basic additive (STR-004-Basic unavailable)") },
            { "pruning.toast_spray", ("Spray Antifungino selezionato. Verrà utilizzato durante la potatura.", "Antifungal spray selected. It will be used during pruning.") },

            // Cryo machine panel
            { "cryo.footer_unavailable", ("⚠ CRYO MACHINE NON DISPONIBILE", "⚠ CRYO MACHINE UNAVAILABLE") },
            { "cryo.slots_occupied", ("SLOT OCCUPATI: {n} / {total}", "SLOTS OCCUPIED: {n} / {total}") },
            { "cryo.slot_free", ("Slot disponibile", "Slot available") },
            { "cryo.badge_active", ("ATTIVO", "ACTIVE") },
            { "cryo.badge_empty", ("VUOTO", "EMPTY") },
            { "cryo.level", ("Lvl {n}", "Lv. {n}") },

            // Seed storage panel
            { "seed_storage.conn_on", ("CONNESSIONE: STABILE", "CONNECTION: STABLE") },
            { "seed_storage.conn_off", ("CONNESSIONE: OFFLINE", "CONNECTION: OFFLINE") },
            { "seed_storage.temp_on", ("❄ TEMP: -18°C", "❄ TEMP: -18°C") },
            { "seed_storage.temp_off", ("TEMP: —", "TEMP: —") },
            { "seed_storage.power_on", ("⚡ ALIMENT.: ON", "⚡ POWER: ON") },
            { "seed_storage.power_off", ("⚡ ALIMENT.: OFF", "⚡ POWER: OFF") },
            { "seed_storage.sys_nominal", ("STATO SISTEMA: NOMINALE", "SYSTEM STATUS: NOMINAL") },
            { "seed_storage.sys_off", ("STATO SISTEMA: OFFLINE", "SYSTEM STATUS: OFFLINE") },
            { "seed_storage.occupied", ("OCCUPATI: {n}/6", "OCCUPIED: {n}/6") },
            { "seed_storage.available", ("DISPONIBILI: {n}", "AVAILABLE: {n}") },
            { "seed_storage.cost_on", ("COSTO GIORN.: {cost} CRY", "DAILY COST: {cost} CRY") },
            { "seed_storage.cost_off", ("COSTO GIORN.: 0 CRY (OFF)", "DAILY COST: 0 CRY (OFF)") },
            { "seed_storage.ap", ("AP: {n}", "AP: {n}") },
            { "seed_storage.btn_off", ("SPEGNI", "TURN OFF") },
            { "seed_storage.btn_on", ("ACCENDI", "TURN ON") },
            { "seed_storage.slot_n", ("SLOT {n}", "SLOT {n}") },
            { "seed_storage.slot_locked", ("SLOT BLOCCATO", "SLOT LOCKED") },
            { "seed_storage.slot_empty", ("SLOT VUOTO", "EMPTY SLOT") },
            { "seed_storage.slot_ready", ("Pronto per lo storage", "Ready for storage") },
            { "seed_storage.qty", ("Quantità: {n}", "Quantity: {n}") },
            { "seed_storage.inv_empty", ("— vuoto", "— empty") },
            { "seed_storage.chrome.left_title", ("INVENTARIO GIOCATORE", "PLAYER INVENTORY") },
            { "seed_storage.chrome.left_subtitle", ("DEPOSITO LOCALE", "LOCAL DEPOSIT") },
            { "seed_storage.chrome.right_title", ("INTERFACCIA SEED STORAGE", "SEED STORAGE INTERFACE") },
            { "seed_storage.chrome.right_subtitle", ("NODO VAULT EXT-002", "VAULT NODE EXT-002") },
            { "seed_storage.chrome.tip", ("Seleziona uno o più item per depositare, o uno slot per prelevare.", "Select one or more items to deposit, or a slot to withdraw.") },
            { "seed_storage.chrome.btn_deposit", ("→  TRASFERISCI ALLO STORAGE  (1 AP)", "→  TRANSFER TO STORAGE  (1 AP)") },
            { "seed_storage.chrome.btn_withdraw", ("←  PRELEVA DALLO STORAGE  (1 AP)", "←  WITHDRAW FROM STORAGE  (1 AP)") },
            { "seed_storage.chrome.cat_botanical", ("BOTANICA", "BOTANY") },
            { "seed_storage.chrome.cat_seeds", ("SEMI", "SEEDS") },
            { "seed_storage.chrome.cat_spores", ("SPORE", "SPORES") },
            { "seed_storage.chrome.capacity", ("CAPIENZA MAX: 6", "MAX CAPACITY: 6") },
            { "seed_storage.chrome.vitality", ("VITALITÀ", "VIABILITY") },
            { "seed_storage.chrome.log_title", ("■  LOG DI SISTEMA", "■  SYSTEM LOG") },
            { "seed_storage.chrome.unlock_btn", ("+ SBLOCCA: +3 CRY/giorno", "+ UNLOCK: +3 CRY/day") },
            { "seed_storage.log.init_cryo", ("> Sistema inizializzato — Camere crioniche stabili", "> System initialized — cryo chambers stable") },
            { "seed_storage.log.init_ready", ("> Connessione stabilita — Terminale pronto", "> Connection established — terminal ready") },
            { "seed_storage.log.power_on", ("> Alimentazione ON — crioconservazione attiva.", "> Power ON — cryo preservation active.") },
            { "seed_storage.log.power_off", ("> Alimentazione OFF — decadimento attivo sui contenuti.", "> Power OFF — decay active on stored contents.") },
            { "seed_storage.log.unlock", ("> Slot 4-6 sbloccati (tier 2 · 3 CRY/giorno per slot occupato).", "> Slots 4-6 unlocked (tier 2 · 3 CRY/day per occupied slot).") },
            { "seed_storage.log.no_selection_items", ("> Nessun item selezionato.", "> No items selected.") },
            { "seed_storage.log.deposit_ok", ("> Depositati {n} item (1 AP).", "> Deposited {n} item(s) (1 AP).") },
            { "seed_storage.log.deposit_fail", ("> Deposito fallito: {reason}.", "> Deposit failed: {reason}.") },
            { "seed_storage.log.no_slots", ("> Nessuno slot selezionato.", "> No slots selected.") },
            { "seed_storage.log.withdraw_ok", ("> Prelevati {n} slot (1 AP).", "> Withdrew {n} slot(s) (1 AP).") },
            { "seed_storage.log.withdraw_fail", ("> Prelievo fallito: {reason}.", "> Withdrawal failed: {reason}.") },
            { "seed_storage.err.no_ap", ("AP insufficienti", "Not enough AP") },
            { "seed_storage.err.no_room", ("spazio esaurito", "no space left") },
            { "seed_storage.err.ineligible", ("item non ammesso", "item not allowed") },
            { "seed_storage.err.not_in_inventory", ("item non più disponibile", "item no longer available") },
            { "seed_storage.err.remove_failed", ("errore interno", "internal error") },
            { "seed_storage.err.bad_slot", ("slot non valido", "invalid slot") },
            { "seed_storage.err.empty", ("selezione vuota", "empty selection") },
            { "seed_storage.err.generic", ("errore", "error") },

            // Wardrobe
            { "wardrobe.outfit", ("Outfit {i}/{n}", "Outfit {i}/{n}") },

            // Plant terminal (subset)
            { "plant_terminal.suggestions_tooltip", ("Suggerimenti live per {pot}", "Live suggestions for {pot}") },
            { "plant_terminal.driver_fertilizer_low", ("Fertilizzante basso", "Low fertilizer") },
            { "plant_terminal.driver_fertilizer_high", ("Fertilizzante in eccesso", "Excess fertilizer") },
            { "plant_terminal.reason_empty_pot", ("Vaso vuoto: pianta prima un seme.", "Empty pot: plant a seed first.") },
            { "plant_terminal.reason_action_na", ("Azione non disponibile ora.", "Action not available right now.") },
            { "plant_terminal.driver_light_crit", ("Light stress critico", "Critical light stress") },
            { "plant_terminal.driver_light_high", ("Light stress alto", "High light stress") },
            { "plant_terminal.driver_infested", ("INFESTATA — esegui PRUNE", "INFESTED — run PRUNE") },
            { "plant_terminal.driver_mold_crit", ("Rischio muffa critico", "Critical mold risk") },
            { "plant_terminal.driver_mold", ("Rischio muffa", "Mold risk") },
            { "plant_terminal.driver_hydration_low", ("Idratazione bassa", "Low hydration") },
            { "plant_terminal.driver_overwater", ("Sovra-irrigazione", "Overwatering") },

            // End of day (subset — snapshot, dawn, forecast headers)
            { "eod.day_from", ("GIORNO {n}", "DAY {n}") },
            { "eod.day_to", ("→ GIORNO {n}", "→ DAY {n}") },
            { "eod.snapshot_title", ("SPORAE — Giorno {day}", "SPORAE — Day {day}") },
            { "eod.snapshot_date", ("Data di sistema: {date}", "System date: {date}") },
            { "eod.snapshot_vault", ("Stato Vault: operativo", "Vault status: operational") },
            { "eod.snapshot_ph_empty", ("pH Cupola: —", "Dome pH: —") },
            { "eod.snapshot_ph", ("pH Cupola: {ph} ({band})", "Dome pH: {ph} ({band})") },
            { "eod.snapshot_actions", ("Azioni usate: {used}/{max}", "Actions used: {used}/{max}") },
            { "eod.snapshot_cry", ("CRY guadagnati: {earned}, spesi: {spent}", "CRY earned: {earned}, spent: {spent}") },
            { "eod.snapshot_balance", ("Saldo: {cry} CRY", "Balance: {cry} CRY") },
            { "eod.snapshot_harvest", ("Raccolto: {list}.", "Harvested: {list}.") },
            { "eod.snapshot_water", ("Annaffiati {list}.", "Watered {list}.") },
            { "eod.snapshot_pot_prefix", ("POT {n}", "POT {n}") },
            { "eod.activity_none", ("Nessuna attività registrata.", "No activity recorded.") },
            { "eod.drift_title", ("Deriva e conseguenze:", "Drift and consequences:") },
            { "eod.drift_ph", ("Andamento pH: {ph} ({band}), deriva {drift}", "pH trend: {ph} ({band}), drift {drift}") },
            { "eod.drift_ph_empty", ("Andamento pH: —", "pH trend: —") },
            { "eod.drift_breathe", ("La Cupola respira.", "The Dome breathes.") },
            { "eod.notes_header", ("[NOTE E TAG]", "[NOTES & TAGS]") },
            { "eod.notes_inventory", ("Inventario ........ {v}", "Inventory ........ {v}") },
            { "eod.notes_seed", ("Deposito semi ..... {v}", "Seed vault ........ {v}") },
            { "eod.notes_research", ("Ricerca ........... IN ATTESA", "Research ........ PENDING") },
            { "eod.notes_food", ("Cibo cucina ....... {v}", "Kitchen food ...... {v}") },
            { "eod.notes_water", ("Acqua potabile .... {v}", "Drinking water .... {v}") },
            { "eod.notes_warning_label", ("Avviso .............. ", "Alert .............. ") },
            { "eod.notes_mold", ("Rischio muffa nel POT {list}.", "Mold risk in POT {list}.") },
            { "eod.forecast_today", ("[OGGI]\n", "[TODAY]\n") },
            { "eod.forecast_tomorrow", ("[PREVISIONE DOMANI]\n", "[TOMORROW FORECAST]\n") },
            { "eod.forecast_actions_avail", ("Azioni disponibili: {n}", "Actions available: {n}") },
            { "eod.forecast_ph_drift", ("Deriva pH prevista: {v}", "Predicted pH drift: {v}") },
            { "eod.forecast_risks", ("Rischi ambientali: —", "Environmental risks: —") },
            { "eod.forecast_missions", ("Missioni attive: —", "Active missions: —") },
            { "eod.forecast_research_done", ("Ricerca completata: → Nuovo frammento di lore sbloccato.", "Research complete: → New lore fragment unlocked.") },
            { "eod.diario_harvest", ("Oggi hai raccolto. Le spore ricordano.", "You harvested today. The spores remember.") },
            { "eod.diario_water", ("L’acqua è scorsa. La vita è stata sostenuta.", "Water flowed. Life was sustained.") },
            { "eod.diario_footer", ("Sistema SPORAE: registrazione completata.\nIntegrità memoria: 100%. Prossimo risveglio tra: —\nBuona notte, Biologo. O chiunque tu sia.", "SPORAE system: log complete.\nMemory integrity: 100%. Next wake: —\nGood night, Biologist. Or whoever you are.") },
            { "eod.dawn_title", ("RIEPILOGO ALBA", "DAWN SUMMARY") },
            { "eod.dawn_sub", ("GIORNO {day} – VARIAZIONI NOTTURNE", "DAY {day} – NIGHT CHANGES") },
            { "eod.dawn_mutation", ("Indice di mutazione: {v}", "Mutation index: {v}") },
            { "eod.dawn_mutation_empty", ("Indice di mutazione: —", "Mutation index: —") },
            { "eod.dawn_ph_drift", ("Deriva pH: {v}{trend}", "pH drift: {v}{trend}") },
            { "eod.dawn_cond", ("Condensazione: {v}", "Condensation: {v}") },
            { "eod.dawn_cond_empty", ("Condensazione: —", "Condensation: —") },
            { "eod.dawn_grate", ("G-rate: +{n}", "G-rate: +{n}") },
            { "eod.dawn_cry", ("Saldo CRY (previsione fine giorno): {cry} (solo costi fissi)", "CRY balance (end-of-day forecast): {cry} (fixed costs only)") },
            { "eod.dawn_trend_acid", (" (tendenza acida)", " (acid trend)") },
            { "eod.dawn_trend_alk", (" (tendenza alcalina)", " (alkaline trend)") },
            { "eod.tip_prefix", ("SUGGERIMENTO: ", "TIP: ") },
            { "eod.tt_mutation_title", ("[INDICE DI MUTAZIONE]", "[MUTATION INDEX]") },
            { "eod.tt_mutation_desc", ("L’indice di mutazione riflette la deriva genetica nella Cupola. Le condizioni notturne possono spostare la probabilità di mutazione.", "The mutation index reflects genetic drift in the Dome. Night conditions can shift mutation probability.") },
            { "eod.tt_mutation_tip", ("Monitora le zone a mutazione elevata e usa stabilizzatori in Lab se necessario.", "Watch high-mutation zones and use Lab stabilizers if needed.") },
            { "eod.tt_ph_title", ("[DERIVA pH RILEVATA]", "[DETECTED pH DRIFT]") },
            { "eod.tt_ph_desc_neutral", ("L’andamento del pH è monitorato durante la notte. La deriva influenza la crescita delle piante e la probabilità di mutazione.", "pH is monitored overnight. Drift affects plant growth and mutation odds.") },
            { "eod.tt_ph_desc_shift", ("L’ambiente della Cupola si è spostato verso {dir}. Influenza i modelli di crescita e la probabilità di mutazione.", "The Dome environment shifted toward {dir}. It affects growth patterns and mutation odds.") },
            { "eod.tt_ph_dir_acid", ("l’acidità", "acidity") },
            { "eod.tt_ph_dir_alk", ("l’alcalinità", "alkalinity") },
            { "eod.tt_ph_tip", ("Usa substrati alcalini o attiva stabilizzatori di pH in Lab per contrastare la deriva.", "Use alkaline substrates or enable pH stabilizers in Lab to counter drift.") },
            { "eod.tt_cond_title", ("[VARIAZIONE LIVELLO CONDENSAZIONE]", "[CONDENSATION LEVEL CHANGE]") },
            { "eod.tt_cond_desc", ("La condensazione si è accumulata durante la notte. L’umidità eccessiva favorisce la muffa ma beneficia le specie dipendenti dall’acqua.", "Condensation built overnight. Excess humidity favors mold but helps water-dependent species.") },
            { "eod.tt_cond_tip", ("Controlla le piante per segni di muffa. Valuta di raccogliere presto le specie sensibili alla condensazione.", "Check plants for mold. Consider harvesting condensation-sensitive species early.") },
            { "eod.tt_grate_title", ("[AGGIORNAMENTO G-RATE]", "[G-RATE UPDATE]") },
            { "eod.tt_grate_desc", ("Contributo giornaliero al tasso di crescita dai sistemi. Influenza accumulo risorse e sviluppo delle piante.", "Daily contribution to growth rate from systems. Affects resource buildup and plant development.") },
            { "eod.tt_grate_tip", ("Massimizza il G-rate bilanciando attività in Cupola e Lab.", "Maximize G-rate by balancing Dome and Lab activity.") },
            { "eod.tt_cry_title", ("[PREVISIONE SALDO CRY]", "[CRY BALANCE FORECAST]") },
            { "eod.tt_cry_desc", ("CRY previsti a fine giornata considerando solo i costi fissi (es. energia). Non include azioni variabili.", "CRY at end of day from fixed costs only (e.g. power). Variable actions not included.") },
            { "eod.tt_cry_tip", ("Assicurati di avere CRY sufficienti prima della notte per coprire i costi fissi.", "Ensure enough CRY before night to cover fixed costs.") },
            { "eod.snapshot_plant", ("Hai piantato un seme di {plant} nel POT {pot}.", "You planted a {plant} seed in POT {pot}.") },
            { "eod.snapshot_light", ("Hai modificato le luci LED nel POT {pot}.", "You changed LED lights in POT {pot}.") },
            { "eod.snapshot_fertilize", ("Hai applicato fertilizzante nel POT {pot}.", "You applied fertilizer in POT {pot}.") },
            { "eod.snapshot_prune", ("Hai potato la pianta nel POT {pot}.", "You pruned the plant in POT {pot}.") },
            { "eod.snapshot_started", ("Azione avviata sul POT {pot}.", "Action started on POT {pot}.") },
            { "eod.lab_extractor", ("Hai estratto {out} da {input}.", "You extracted {out} from {input}.") },
            { "eod.lab_fusion", ("Hai completato la fusione di due Spore ({desc}) nella Stazione di Fusione.", "You completed fusion of two Spores ({desc}) at the Fusion station.") },
            { "eod.lab_generic", ("Hai usato il {lab}.", "You used the {lab}.") },
            { "eod.lab_extract_fallback", ("estrazione", "extraction") },
            { "eod.lab_two_spores", ("due Spore", "two spores") },
            { "eod.lab_spores_unit", ("{n} spore", "{n} spore(s)") },
            { "eod.conditions_header", ("Condizioni attive:", "Active conditions:") },
            { "eod.condition_line", ("  POT {pot}: {sev} (rischio muffa se non trattato domani).", "  POT {pot}: {sev} (mold risk if untreated tomorrow).") },
            { "eod.sev_infest", ("Infestazione", "Infestation") },
            { "eod.sev_mold_high", ("Rischio muffa grave", "Severe mold risk") },
            { "eod.sev_mold_low", ("Rischio muffa lieve", "Mild mold risk") },
            { "eod.seed_preseed", ("{n} Pre-Seed", "{n} Pre-seed(s)") },
            { "eod.drift_placeholder", ("Conseguenza: pH stabilizzato / nota ambientale [placeholder: collegare a eventi]", "Outcome: pH stabilized / ambient note [placeholder: hook events]") },
            { "eod.kitchen_veg", ("Ortaggi", "Vegetables") },
            { "eod.kitchen_fungus", ("Funghi", "Fungi") },
            { "eod.kitchen_meat", ("Carne", "Meat") },
            { "eod.kitchen_food", ("Cibo", "Food") },
            { "eod.kitchen_growing", ("{type} in corso ({days} giorno/i rimanenti)", "{type} in progress ({days} day(s) left)") },
            { "eod.kitchen_ready", ("{type} pronto per il raccolto", "{type} ready to harvest") },
            { "eod.kitchen_none", ("Nessun cibo in produzione.", "No food in production.") },
            { "eod.water_none", ("Nessuna potabilizzazione in corso.", "No purification running.") },
            { "eod.water_ready", ("{n} unità di acqua potabile pronte per la raccolta.", "{n} unit(s) of drinking water ready to collect.") },
            { "eod.water_progress", ("Potabilizzazione in corso.", "Purification in progress.") },
            { "eod.forecast_actions_today", ("Azioni usate: {used} / {max}", "Actions used: {used} / {max}") },
            { "eod.forecast_cry_today", ("CRY guadagnati: {earned}, spesi: {spent}", "CRY earned: {earned}, spent: {spent}") },
            { "eod.forecast_ph_line", ("pH: {ph} ({band})", "pH: {ph} ({band})") },
            { "eod.forecast_reputations", ("Reputazioni: —", "Reputations: —") },

            // Gameplay feedback (PotActions failure reasons, Extractor world label)
            { "gameplay.extractor.input_fruit", ("frutto", "fruit") },
            { "gameplay.pot.no_seed", ("Nessun seme disponibile", "No seed available") },
            { "gameplay.pot.seed_unavailable", ("Seme '{id}' non disponibile", "Seed '{id}' unavailable") },
            { "gameplay.pot.insufficient_actions", ("Azioni insufficienti", "Insufficient actions") },
            { "gameplay.pot.insufficient_resources", ("Risorse insufficienti", "Insufficient resources") },
            { "gameplay.pot.spray_invalid", ("Additivo non valido", "Invalid additive") },
            { "gameplay.pot.spray_unknown", ("Additivo sconosciuto: {id}", "Unknown additive: {id}") },
            { "gameplay.pot.spray_unavailable", ("Additivo non disponibile", "Additive unavailable") },
            { "gameplay.pot.spray_consume_fail", ("Impossibile consumare additivo", "Could not consume additive") },
            { "gameplay.pot.prune_additive_missing", ("Additivo basico (STR-004-Basic) non disponibile", "Basic additive (STR-004-Basic) unavailable") },
            { "gameplay.pot.prune_consume_fail", ("Impossibile consumare additivo basico", "Could not consume basic additive") },
            { "gameplay.pot.prune_config_missing", ("Configurazione potatura non trovata", "Pruning configuration not found") },
            { "gameplay.pot.no_fruit", ("Nessun frutto disponibile", "No fruit available") },
            { "gameplay.pot.empty_pot", ("Vaso vuoto", "Empty pot") },
            { "gameplay.pot.fertilizer_unavailable", ("Fertilizzante '{id}' non disponibile", "Fertilizer '{id}' unavailable") },
            { "gameplay.pot.plantdata_missing", ("PlantData non trovato", "PlantData not found") },
            { "eod.inv_spores", ("{n} spore", "{n} spore(s)") },
            { "eod.inv_spores_detail", ("{n} spore (Puri: {pure}, Malvagi: {evil}, Standard: {standard})", "{n} spore(s) (Pure: {pure}, Evil: {evil}, Standard: {standard})") },
            { "eod.inv_seeds", ("{n} semi", "{n} seed(s)") },
            { "eod.inv_reagents", ("{n} reagenti", "{n} reagent(s)") },

            // Legacy keys kept while older controllers migrate to dotted keys.
            { "menu_options", ("Opzioni", "Options") },
            { "menu_load", ("Carica", "Load") },
            { "menu_save", ("Salva", "Save") },
            { "menu_continue", ("Continua", "Continue") },
            { "menu_new_game", ("Nuova partita", "New Game") },
            { "menu_quit", ("Esci", "Quit") },
            { "options_sound_volume", ("Volume suoni", "Sound Volume") },
            { "options_music_volume", ("Volume musica", "Music Volume") },
            { "options_language", ("Lingua", "Language") },
            { "notifications_title", ("NOTIFICHE", "NOTIFICATIONS") },
            { "added_to_inventory", ("AGGIUNTO ALL'INVENTARIO", "ADDED TO INVENTORY") }
        };

        public static bool IsItalian =>
            GameLanguageSettings.GetEffectiveLanguage() == GameLanguage.Italian;

        /// <summary>Restituisce la stringa localizzata per la chiave. Se assente, restituisce la chiave.</summary>
        public static string GetString(string key)
        {
            if (string.IsNullOrEmpty(key))
                return string.Empty;

            if (Table.TryGetValue(key, out var pair))
                return Pick(pair.It, pair.En);

            return key;
        }

        public static string GetString(string key, IReadOnlyDictionary<string, string> args)
        {
            return Format(GetString(key), args);
        }

        public static string Pick(string italian, string english)
        {
            if (IsItalian)
                return string.IsNullOrEmpty(italian) ? english : italian;
            return string.IsNullOrEmpty(english) ? italian : english;
        }

        public static string Format(string template, IReadOnlyDictionary<string, string> args)
        {
            if (string.IsNullOrEmpty(template))
                return string.Empty;

            if (args == null || args.Count == 0)
                return template;

            return TokenRegex.Replace(template, match =>
            {
                var key = match.Groups[1].Value;
                return args.TryGetValue(key, out var value) ? value : match.Value;
            });
        }

        /// <summary>Registra una coppia IT/EN per una chiave (utile per estensioni).</summary>
        public static void Register(string key, string textIt, string textEn)
        {
            Table[key] = (textIt, textEn);
        }
    }
}
